# artifacthub                                       https://artifacthub.io/packages/helm/grafana/promtail
# values.yaml                                       https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: promtail-helm-chart
name: &name promtail
version: 6.16.6                                    # https://github.com/grafana/helm-charts/compare/promtail-6.6.2...promtail-6.7.4
repo: https://grafana.github.io/helm-charts
releaseName: *name
namespace: promtail
includeCRDs: false
valuesFile: values.yaml
valuesMerge: override                 # merge, override or replace
valuesInline:
  config:
    clients:
      - url: http://loki-distributed-gateway.loki.svc.cluster.local/loki/api/v1/push
  #  lokiAddress: http://loki-distributed-gateway.loki.svc.cluster.local/loki/api/v1/push
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
