apiVersion: khelm.mgoltzsche.github.com/v2
kind: ChartRenderer
metadata:
  name: &name argo-cd
  namespace: argocd
repository: https://argoproj.github.io/argo-helm
chart: *name
version: 5.2.0
include:
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
values:
  ## Custom resource configuration
  crds:
    # -- Install and upgrade CRDs
    install: true
    # -- Keep CRDs on chart uninstall
    keep: false
    # -- Annotations to be added to all CRDs
    annotations: {}