---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-500"
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/kube-components-stack/kustomization.git
              revision: HEAD
              directories:
                - path: "rendered-manifests/addons/crds/*"
                # - path: rendered-manifests/addons/crds/argo-cd
                #   exclude: false
                # - path: rendered-manifests/addons/crds/cert-manager
                #   exclude: false
                # - path: rendered-manifests/addons/crds/kube-prometheus-stack
                #   exclude: false
                # - path: rendered-manifests/addons/crds/kyverno
                #   exclude: false
                - path: rendered-manifests/addons/crds/metallb
                  exclude: true
                # - path: rendered-manifests/addons/crds/cert-manager
                #   exclude: false
                # - path: rendered-manifests/addons/crds/sealed-secrets
                #   exclude: false
          - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}-addons-crd'             # for mono  cluster
      # name: '{{path.basename}}-{{name}}'  # for multi cluster
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "rendered-manifests/addons/crds/{{path.basename}}/base;rendered-manifests/addons/crds/{{path.basename}}/overlays/{{name}}"
    spec:
      project: addons-crds
      info: []
      source:
        repoURL: https://github.com/kube-components-stack/kustomization.git
        targetRevision: HEAD
        path: "rendered-manifests/addons/crds/{{path.basename}}/overlays/{{name}}"
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 2m
          limit: 5
        # https://argo-cd.readthedocs.io/en/stable/user-guide/sync-options/
        syncOptions:
          - Replace=true