---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-500"
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/kube-components-stack/kustomization.git
              revision: HEAD
              directories:
                - path: "rendered-manifests/core/crds/*"
          - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}-core-crd'             # for mono  cluster
      # name: '{{path.basename}}-{{name}}'           # for multi cluster
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "rendered-manifests/core/crds/{{path.basename}}"
    spec:
      project: core-crds
      info: []
      source:
        repoURL: https://github.com/kube-components-stack/kustomization.git
        targetRevision: HEAD
        path: "rendered-manifests/core/crds/{{path.basename}}/overlays/{{name}}"
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 2m
          limit: 5
        syncOptions:
          - Replace=true