# https://aquasecurity.github.io/trivy-operator/v0.7.1/operator/
# https://aquasecurity.github.io/trivy
# https://github.com/aquasecurity/trivy-operator/blob/main/deploy/helm/values.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: trivy-operator-helm-chart
name: &name trivy-operator
version: v0.7.1
repo: https://aquasecurity.github.io/helm-charts
releaseName: *name
namespace: trivy-system
includeCRDs: false
valuesFile: values.yaml
valuesMerge: override                 # merge, override or replace
valuesInline:
  trivy:
    ignoreUnfixed: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
  resources:
    requests:
      cpu: 300m
      memory: 300M
    limits:
      cpu: 1
      memory: 1024M
