apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
  # namespace: argocd
spec:
  strategy:
    rollingUpdate: null
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
spec:
  strategy:
    rollingUpdate: null
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications
spec:
  strategy:
    rollingUpdate: null
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
spec:
  strategy:
    rollingUpdate: null
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  strategy:
    rollingUpdate: null
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  strategy:
    rollingUpdate: null
    type: Recreate