# https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_helmchartinflationgenerator_
apiVersion: builtin
kind: HelmChartInflationGenerator
# metadata:
#   name: xxx
chartName: metallb
chartRepoUrl: https://metallb.github.io/metallb
chartVersion: v0.12.1
# https://github.com/kubernetes-sigs/kustomize/blob/master/api/types/helmchartargs.go#L79
# https://cloud.google.com/anthos-config-management/docs/how-to/use-repo-kustomize-helm
# values: values.yaml
# valuesLocal: []
# valuesMerge: values.yaml