apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- namespace.yaml
- job.yaml
- dashboards/14584-1.yaml
- dashboards/12321-2.yaml
- dashboards/13639-2.yaml
- dashboards/13824-2.yaml
- dashboards/14678-1.yaml
- dashboards/13332-12.yaml
- dashboards/9614-1.yaml
- dashboards/14314-2.yaml
- dashboards/11001-1.yaml
- dashboards/10880-1.yaml
- dashboards/15443-2.yaml
- dashboards/12019-2.yaml
- dashboards/14055-5.yaml
- dashboards/13865-6.yaml
- dashboards/15196-3.yaml
# - dashboards/kube-prometheus-stack-alertmanager-overview.yaml
# - dashboards/kube-prometheus-stack-apiserver.yaml
# - dashboards/kube-prometheus-stack-cluster-total.yaml
# - dashboards/kube-prometheus-stack-controller-manager.yaml
# - dashboards/kube-prometheus-stack-etcd.yaml
# - dashboards/kube-prometheus-stack-grafana-overview.yaml
# - dashboards/kube-prometheus-stack-k8s-coredns.yaml
# - dashboards/kube-prometheus-stack-k8s-resources-cluster.yaml
# - dashboards/kube-prometheus-stack-k8s-resources-namespace.yaml
# - dashboards/kube-prometheus-stack-k8s-resources-node.yaml
# - dashboards/kube-prometheus-stack-k8s-resources-pod.yaml
# - dashboards/kube-prometheus-stack-k8s-resources-workloads-namespace.yaml
# - dashboards/kube-prometheus-stack-k8s-resources-workload.yaml
# - dashboards/kube-prometheus-stack-kubelet.yaml
# - dashboards/kube-prometheus-stack-namespace-by-pod.yaml
# - dashboards/kube-prometheus-stack-namespace-by-workload.yaml
# - dashboards/kube-prometheus-stack-node-cluster-rsrc-use.yaml
# - dashboards/kube-prometheus-stack-node-rsrc-use.yaml
# - dashboards/kube-prometheus-stack-nodes-darwin.yaml
# - dashboards/kube-prometheus-stack-nodes.yaml
# - dashboards/kube-prometheus-stack-persistentvolumesusage.yaml
# - dashboards/kube-prometheus-stack-pod-total.yaml
# - dashboards/kube-prometheus-stack-prometheus.yaml
# - dashboards/kube-prometheus-stack-proxy.yaml
# - dashboards/kube-prometheus-stack-scheduler.yaml
# - dashboards/kube-prometheus-stack-workload-total.yaml
- dashboards/16742-1.yaml
- dashboards/12330-1.yaml
- dashboards/12331-1.yaml
