apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: addresspools.metallb.io
  finalizers: []
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bgppeers.metallb.io
  finalizers: []