# https://artifacthub.io/packages/helm/bitnami-labs/sealed-secrets
# https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets
# https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: sealed-secrets-helm-chart
name: sealed-secrets
version: 2.16.1
repo: https://bitnami-labs.github.io/sealed-secrets
releaseName: sealed-secrets
namespace: kube-system
includeCRDs: false
valuesFile: values.yaml
valuesMerge: override                 # merge, override or replace
valuesInline:
  namespace: kube-system