apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCDnSJv+ZvnRXfsVPD/8u8tHMsI1uqDC5ltBvh1foDXcEEGV1KHKSruJorXTkA2ePo63h5Bd33zhjr6n3Fb0dnfQdlt/TSJkNMvs89F+42nC4ooRUmGFkiT4iUUMLgXwUSfmmBIGiaENL+8wq9BIt1L135nlYgbTUTwtYxIMrWyEQcxMw/wAA0QrOr/sbxAe24UmcWahly/ti3zWu4TOPnvjdh+D16rFvTVTmk1/xG/9bz9JbVGhxHUDSUbMbOdUXw55N/LU+n0XjHC2q9Au2Iub7+ESthtmGmuGa/4rfQfOGnqabPq5v8JK9RvW/+J77uC38hqF7haZ0PS8o3FBPv/ote9X4D/EGC/XwaUxtU6lL5mw80u/OiOvQUDb669Qa65A6CW7CdX/sHDHNPk4urIXZST/ijed4XZQDrInEf1lPkxmcOXyzuf7PwfoDt/xqYVesqfheFvAppFVjv4VaNmPw/IjZFX/Khf/IJXL51UCJrgnWYBqA2z1duU0uV3U8wfRBzBIA4OwgbHpwEYHfZnDl/80iIvvQlMjHJXw87dTAA9M4xbSPjsHnweo0BkoYfyPIgJjaY5gamWKmlekckDr2aAQvOmcZoQQZKXNgbgAjH/2VHjFZEgqdwto5z5AZ3ElVdgR94i1PsXP4FPi1DBR4Zy/xwz214AYx0FOQF58PS99FGjdcZDqrxfAcFcBkaPakamCQ==
    admin-user: AgANCg8Q+m5lSlFSfBtoFuyE1unNFhd+hJ8TBMMpPDjpNzcbJK+V6c+FffwgKSCYHqAN8+jsL/i6PsaVXWBYXC3CjLhvyvk7vr3co0woXJoBTKl41AAJJIJujkJQWnu6zCTez2A9UN3Z9nEsNwSwGKwBJExNGCi53kdfetslAXHbsrBwy1nyRqeb+pY/98m/MapfH7hepwPcIn5rbJCtqN4FQd5vuwHGn58lSjryc6VjrazXrTFOJc6iIWntWNqctQStilwXSt6+7SOP3kpWRqc0nAiJWN/xO9AzM97CqXkbEhxEW6NOVwQZEIMjygRUxxcR6QY8cx8HrlL5xCrFJ2bBr1c+N4vuNEhNpi900r7+BOC3DkiNI5MRF58Tr7JJIasCbCdQdB5+t/eq4mCSUjP8IhBNG2VRXS2tu8ya22qXHnIXIM2gPluzLswWPW9fSNy+VT5qC2RodSVgJgXla+M4O2KDPLBTmLQwhfHDeR89GKoQRVKSOUBlp4/+STXvdSiRf4sYs341/GR7uCWK4Mvx3SNz5S2Kix9az+xp4PEX7UDj1Dpz/3NOM3lhxCLTRxh3enDFs/M528ndT5nBU7isI64kyckYwJlGFDE1glshPVaSR+I0c5FK2fs2GtgRMoRZSmhDIPglhQnC+Kak4oSplPd5cNDbsjrfxEGbqF0C14/JCiS1NotbEfXsPWgszYok4QlQSw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
    type: Opaque
