---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kustomization.fullname" . }}
  labels:
    {{- include "kustomization.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    helm.sh/hook-weight: "-5"
    # helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    # helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kustomization.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kustomization.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}