---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-argocd
  labels:
    {{- include "kustomization.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 1
  template:
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      containers:
      - 
        name: kubectl
        command:
        - /bin/sh
        - -c
        - |
          /bin/bash <<'EOF'
            set -euo pipefail
            folder=core/crds
            for crd in $(curl -s https://api.github.com/repos/${OWNER}/${REPO}/contents/${folder}\?ref\=${REF} | jq -r '.[].name'); do
              echo "kubectl apply -k https://github.com/${OWNER}/${REPO}/${folder}/${crd}/overlays/${CLUSTER}-${ENV}/\?ref\=${REF} --server-side=true --force-conflicts"
            done
          EOF
        # kubectl apply -k https://github.com/${OWNER}/${REPO}/${folder}/${crd}/overlays/${cluster}-${env}/\?ref\=${REF} --server-side=true --force-conflicts
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- range $key, $value := .Values.env.fromValues }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Never
      serviceAccountName: {{ include "kustomization.serviceAccountName" . }}
