---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-argocd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kustomization.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 0
  template:
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      volumes:
        {{- with .Values.volumesAndMounts.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - 
        name: kubectl
        command:
        - /bin/sh
        - -c
        - |
          /bin/bash <<'EOF'
            trap "kubectl delete clusterroles.rbac.authorization.k8s.io system:{{ include "kustomization.fullname" . }}" EXIT
            set -euo pipefail
            set -x
            folder=core/crds
            for crd in $(curl -s https://api.github.com/repos/${OWNER}/${REPO}/contents/${folder}\?ref\=${REF} | jq -r '.[].name'); do
              kubectl apply -k https://github.com/${OWNER}/${REPO}/${folder}/${crd}/overlays/${CLUSTER}-${ENV}/\?ref\=${REF} --server-side=true --force-conflicts
            done
          EOF
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","kubectl delete clusterroles.rbac.authorization.k8s.io system:{{ include "kustomization.fullname" . }} 1>> /proc/1/fd/1 2>> /proc/1/fd/2"]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- range $key, $value := .Values.env.fromValues }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          {{- with .Values.volumesAndMounts.volumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      restartPolicy: Never
      serviceAccountName: {{ include "kustomization.serviceAccountName" . }}
