{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
# automountServiceAccountToken: ?
metadata:
  name: {{ include "kustomization.serviceAccountName" . }}
  labels:
    {{- include "kustomization.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    helm.sh/hook-weight: "-10"
    # helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
    # helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
