---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/kube-components-stack/kustomization.git
              revision: HEAD
              directories:
                - path: "cluster-addons/*"
                - path: cluster-addons/argo-cd
                  exclude: false
                - path: cluster-addons/authentik
                  exclude: false
                - path: cluster-addons/cert-manager
                  exclude: false
                - path: cluster-addons/ingress-nginx
                  exclude: false
                - path: cluster-addons/keycloak
                  exclude: false
                - path: cluster-addons/kube-prometheus-stack
                  exclude: false
                - path: cluster-addons/kyverno
                  exclude: false
                - path: cluster-addons/kyverno-policies
                  exclude: false
                - path: cluster-addons/loki-distributed
                  exclude: false
                - path: cluster-addons/metallb
                  exclude: false
                - path: cluster-addons/metrics-server
                  exclude: false
                - path: cluster-addons/minio
                  exclude: false
                - path: cluster-addons/promtail
                  exclude: false
                - path: cluster-addons/sealed-secrets
                  exclude: false
                - path: cluster-addons/vector
                  exclude: false
          - clusters: {}
  template:
    metadata:
      name: 'cluster-addons-{{path.basename}}-{{name}}'
    spec:
      project: default
      info: []
      source:
        repoURL: https://github.com/kube-components-stack/kustomization.git
        targetRevision: HEAD
        path: "cluster-addons/{{path.basename}}/overlays/{{name}}"
        # plugin:
        #   name: argocd-lovely-plugin # https://github.com/crumbhole/argocd-lovely-plugin
        # kustomize:

      destination:
        server: '{{server}}'
        # namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          allowEmpty: false #true
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 2m
          limit: 5
        syncOptions:
          - Validate=false
        # - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
        # - PrunePropagationPolicy=foreground
        # - PruneLast=true
      ignoreDifferences:
      - group: kyverno.io
        kind: ClusterPolicy
        jqPathExpressions:
        - .spec.rules[] | select(.name|test("autogen-."))
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
        - /status
      - group: apps
        kind: Deployment
        jqPathExpressions:
        - '.spec.template.spec.containers[]?.securityContext'
        - '.spec.template.spec.containers[]?.resources'
      - group: apps
        kind: Deployment
        jqPathExpressions:
        - '.spec.template.spec.containers[]?.imagePullPolicy'
      - group: apps
        kind: DaemonSet
        jqPathExpressions:
        - '.spec.template.spec.containers[]?.imagePullPolicy'
      - group: apps
        kind: StatefulSet
        jqPathExpressions:
        - '.spec.template.spec.containers[]?.imagePullPolicy'