---
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#projects
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core-crds
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  clusterResourceWhitelist:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: core-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-500"
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/kube-components-stack/kustomization.git
              revision: HEAD
              directories:
                - path: "core/crds/*"
          - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}-core-crd'             # for mono  cluster
      # name: '{{path.basename}}-{{name}}'           # for multi cluster
    spec:
      project: core-crds
      info: []
      source:
        repoURL: https://github.com/kube-components-stack/kustomization.git
        targetRevision: HEAD
        path: "core/crds/{{path.basename}}/overlays/{{name}}"
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 2m
          limit: 5
        syncOptions:
          - Replace=true