---
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#projects
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: crd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-500"
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/kube-components-stack/kustomization.git
              revision: HEAD
              directories:
                - path: "crds/*"
                # - path: crds/argo-cd
                #   exclude: false
                # - path: crds/cert-manager
                #   exclude: false
                # - path: crds/kube-prometheus-stack
                #   exclude: false
                # - path: crds/kyverno
                #   exclude: false
                - path: crds/metallb
                  exclude: true
                # - path: crds/sealed-secrets
                #   exclude: false
          - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: crd
      info: []
      source:
        repoURL: https://github.com/kube-components-stack/kustomization.git
        targetRevision: HEAD
        path: "crds/{{path.basename}}/overlays/{{name}}"
      destination:
        server: '{{server}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 2m
          limit: 5
        syncOptions:
          - Replace=true