---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kube-components-stack
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/kube-components-stack/kustomization.git
              revision: HEAD
              directories:
                - path: "cluster-addons/*"
          - clusters: {}
  template:
    metadata:
      name: '{{path.basename}}-{{name}}'
    spec:
      project: default
      info: []
      source:
        repoURL: https://github.com/kube-components-stack/kustomization.git
        targetRevision: HEAD
        path: "cluster-addons/{{path.basename}}/overlays/{{name}}"
        # plugin:
        #   name: argocd-lovely-plugin # https://github.com/crumbhole/argocd-lovely-plugin
        # kustomize:

      destination:
        server: '{{server}}'
        # namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 2m
          limit: 5
        syncOptions:
          - Validate=false
        # - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
        # - PrunePropagationPolicy=foreground
        # - PruneLast=true
      ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
        - /status
      - group: apps
        kind: Deployment
        jqPathExpressions:
        - '.spec.template.spec.containers[]?.securityContext'
        - '.spec.template.spec.containers[]?.resources'
      - group: apps
        kind: Deployment
        jqPathExpressions:
        - '.spec.template.spec.containers[]?.imagePullPolicy'
      - group: apps
        kind: DaemonSet
        jqPathExpressions:
        - '.spec.template.spec.containers[]?.imagePullPolicy'
      - group: apps
        kind: StatefulSet
        jqPathExpressions:
        - '.spec.template.spec.containers[]?.imagePullPolicy'