notifications:
  argocdUrl: https://argocd.k8s.lan
  enabled: false
server:
  ingress:
    enabled: true
    ingressClassName: ingress-nginx-admin
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
    - argocd.k8s.lan
    tls:
    - secretName: argocd-tls-certificate
      hosts:
      - argocd.k8s.lan
## Argo Configs
configs:
  secret:
    # -- Create the argocd-secret
    createSecret: false