ingester:
  # https://github.com/grafana/helm-charts/issues/157#issuecomment-919369654
  replicas: 1
  extraArgs:
  - -memberlist.bind-addr=$(MY_POD_IP)
  - -config.expand-env=true
  extraEnv:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: bucket-s3
        key: awsAcessKeyId
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: bucket-s3
        key: awsSecretAcessKey
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
querier:
  # https://github.com/grafana/helm-charts/issues/157#issuecomment-919369654
  replicas: 1
  extraArgs:
  - -memberlist.bind-addr=$(MY_POD_IP)
  - -config.expand-env=true
  extraEnv:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: bucket-s3
        key: awsAcessKeyId
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: bucket-s3
        key: awsSecretAcessKey
  - name: MY_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
