authentik:
  secret_key: "PleaseGenerateA50CharKey"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to sentry.beryju.org, and is fully opt-in
  error_reporting:
    enabled: false
  postgresql:
    password: "ThisIsNotASecurePassword"

ingress:
  enabled: true
  ingressClassName: nginx-01
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: authentik.k8s.lan
      paths:
        - path: "/"
          pathType: Prefix
  tls:
    - secretName: authentik-tls-certificate
      hosts:
      - authentik.k8s.lan
postgresql:
  enabled: false
  postgresqlPassword: "ThisIsNotASecurePassword"
redis:
  enabled: false