## @param provider DNS provider where the DNS records will be created.
## Available providers are:
## - akamai, alibabacloud, aws, azure, azure-private-dns, cloudflare, coredns, designate, digitalocean, google, hetzner, infoblox, linode, rfc2136, transip, oci
##
provider: aws
## AWS configuration to be set via arguments/env. variables
##
aws:
  ## @param aws.region When using the AWS provider, `AWS_DEFAULT_REGION` to set in the environment (optional)
  ##
  region: us-west-1
  ## @param aws.assumeRoleArn When using the AWS provider, assume role by specifying --aws-assume-role to the external-dns daemon
  ##
  assumeRoleArn: arn:aws:iam::477514913822:role/plato-eks-argocd-external-dns-devncoargo-usw1
## @param domainFilters Limit possible target zones by domain suffixes (optional)
##
domainFilters:
- plato-devncoargo.dev-sbr.com
## @param zoneIdFilters Limit possible target zones by zone id (optional)
##
zoneIdFilters:
- Z0240034N25PTWEFTR8B

## ServiceAccount parameters
## https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  ## @param serviceAccount.annotations Additional Service Account annotations
  ##
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::477514913822:role/plato-eks-argocd-external-dns-devncoargo-usw1
