alertmanager:
  ingress:
    enabled: true
    ingressClassName: nginx-01
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - alertmanager.k8s.lan
    pathType: Prefix
    tls:
    - secretName: alertmanager-tls-certificate
      hosts:
      - alertmanager.k8s.lan
grafana:
  # https://grafana.com/docs/grafana/latest/administration/configuration/
  grafana.ini:
    server:
      root_url: https://grafana.k8s.lan
    # https://grafana.com/docs/grafana/next/setup-grafana/configure-security/configure-authentication/generic-oauth/
    auth.generic_oauth:
      enabled: true
      name: Keycloak
      allow_sign_up: "true"
      scopes: profile,email,groups
      client_id: grafana
      client_secret: iagsmFWVLS5DcEoP9SgGCE3OFAG4g5VF
      auth_url:   https://keycloak.k8s.lan/realms/master/protocol/openid-connect/auth
      token_url:  https://keycloak.k8s.lan/realms/master/protocol/openid-connect/token
      api_url:    https://keycloak.k8s.lan/realms/master/protocol/openid-connect/userinfo
      role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-dev') && 'Editor' || 'Viewer'
      tls_skip_verify_insecure: "true"
  admin:
    existingSecret: grafana-secret
  persistence:
    size: 256Mi
  ingress:
    enabled: true
    ingressClassName: nginx-01
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - grafana.k8s.lan
    pathType: Prefix
    tls:
    - secretName: grafana-tls-certificate
      hosts:
      - grafana.k8s.lan
prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx-01
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - prometheus.k8s.lan
    pathType: Prefix
    tls:
    - secretName: prometheus-tls-certificate
      hosts:
      - prometheus.k8s.lan
  prometheusSpec:
    retention: 1d
    retentionSize: 1GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
