apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgCj0+EDAk+1E4QRXhmCfu2RpDcKWWcxzxUo7cSfXsLv4w9k+ixBHpjNDIAU7S1K1lWIOGl+PxKghAp3bm3Xj3tKoxgjXGk7DKKDa5GJP6Nu9aDKG9BVxvegryYoEG7Zv0SwI5APtEQnFFB2/QWHjSgxhY1AwVxk53FDOhRU4shPcZUZwLL7S6qzv4aQI9Js6HCU8pn/haL0tH09w42Z18HxPCGnHs8l3zZ2Ecly6UcvhhyLjfAUW7mFVtwy+s/RwEaghu6MuFRRTc+Bt7WGBCLpKILUxvDvL4RvfblqyWzeryzqUNXfjUh0MJim9V2xoXw3FRWUvmUCdJi4kGmCsbtHaePrjVHL9gyU93GPvKrnsDzuDvhlf5SeI7kUs9HcJOFpLrmu6p0jokWEdq0DWE4VQRrHPV02GHCfNvYJ+3hanQYbARZwHzbPmbikkwj2QMBISi7unItOQIJKg+XSEYKQzXbrHne6qOxg/cr6c7SYP7UQyfPuQehDOEveNps1WTlSDa14BeSuSQ8xKdOPCUebRRM0twa7rJBjJoanFG7Gpm6Opw/Zm1u/hhHKQCN1bcBVgy6/7223FnHPLJs9RDDbIk4zmSc2ui04qbeoeInQ9c4swWoQ69FmM7EBV8JyBn8pavDTBtiunn+BQHb1L6GTo4vbzeLhYuKjvtSv3vyyp4KqjAY/5P/Utk71OXgYMvpz1EzJ
    management-password: AgBQlkfDtcDsIvztAyRfd6lPUFDcojRaoiLLt7PRUotojTQhxRAiSSWSfZe1TtAfnUSg9/r/iFLDCCWUxscAWMdDg0cwvhp1zACFOsdOKrG7CY8/j5xbjbjdp+nGIQmxliubSFgXAyu3pcVGWNwIS74WL69rf8bchdC1HNarMxX1eAEEQLiATF+42EYqmRkCyYoyCqkK8Pq1K4mYA2fjbhCrM2QEcYZ1GqGYhLDa3TSiPX0MuNmv1AJftk6lfUio6aNMmvGii1WnZNeiem2tbMuxYyrWbofQ2Y1QdxXAEz1JXFAeMfJwSmCJKQsyY8RnbQQ3+NGG3HxOwLwFTyQgn/2yOTIwc6xXGytTS4I3ly8whUpu/W3VlUKL9rgU+dPf1jtjaKF/3QWGWlKHbi8JZ60XVDkDm2pr9rpKa/uKkixd8Ro8pPpLZxPFlbqHV3nBjjRT3efAhgm/+gXALykEl0pWB/eNX0KICOw9gkjPLe590M239iphmAdEmwt3+ySBu/aUvYaAvl/nTKKOuwQIdeh1vLuPHVaIeuJ4ehOGc2MDndwN4k8LtoNosvDLsO1iQ5hxdAjLG2iqPFj2KDC88SgDQhEJHTLrvR6TZ9VsvSh7c8jNeOxcIigBa3qvZ5GfirUIakuKg+aNjj4HOQ/vbip7CbXTm1VWNIC2hEUdo5nh0hOgrPBsu845hOhiWX5/Ox8WO1CT8Jmt
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak
      namespace: keycloak
    type: Opaque
