auth:
  existingSecret:
    name: keycloak-auth
    keyMapping:
      admin-password: admin-password
      management-password: management-password
ingress:
  enabled: true
  ingressClassName: nginx-01
  hostname: keycloak.k8s.lan
  extraTls:
  - secretName: keycloak-ca #keycloak-tls-certificate
    hosts:
      - keycloak.k8s.lan
keycloakConfigCli:
  enabled: true