# extraEnvVars:
# - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
#   value: "true"

# - name: PROXY_ADDRESS_FORWARDING
#   value: "true"

# - name: KEYCLOAK_FRONTEND_URL
#   value: "https://keycloak.k8s.lan/auth"

# - name: KEYCLOAK_EXTRA_ARGS
#   value: "-Dkeycloak.frontendUrl=https://keycloak.k8s.lan/auth"

## @param proxy reverse Proxy mode edge, reencrypt, passthrough or none
## ref: https://www.keycloak.org/server/reverseproxy
##
proxy: edge # passthrough/edge/none/reencrytpt
auth:
  existingSecret:
    name: keycloak-auth
    keyMapping:
      admin-password: admin-password
      management-password: management-password
ingress:
  enabled: true
  path: /*
  ingressClassName: nginx-01
  hostname: keycloak.k8s.lan
  extraTls:
  - secretName: keycloak-ca #keycloak-tls-certificate
    hosts:
      - keycloak.k8s.lan
  annotations:
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For, X-Forwarded-Proto, DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    # nginx.ingress.kubernetes.io/affinity: cookie
    # nginx.ingress.kubernetes.io/session-cookie-name: AUTH_SESSION_ID_LEGACY
    nginx.org/server-snippets: |
      location /auth {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $host;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
service:
  type: ClusterIP
keycloakConfigCli:
  enabled: true
  command:
  - java
  - '-jar'
  # - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-17.0.0.jar
  - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-18.0.1.jar
  extraEnvVars:
  - name: IMPORT_FILES_LOCATIONS
    value: /secret/*
  extraVolumeMounts:
  - mountPath: /secret
    name: cfg
    readOnly: true
  extraVolumes:
  - name: cfg
    secret:
      secretName: keycloak-config