auth:
  existingSecret:
    name: keycloak-auth
    keyMapping:
      admin-password: admin-password
      management-password: management-password
ingress:
  enabled: true
  ingressClassName: nginx-01
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hostname: keycloak.k8s.lan
  extraTls:
  - secretName: keycloak-tls-certificate
    hosts:
      - keycloak.k8s.lan