# extraEnvVars:
# - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
#   value: "true"

## @param proxy reverse Proxy mode edge, reencrypt, passthrough or none
## ref: https://www.keycloak.org/server/reverseproxy
##
proxy: passthrough
auth:
  existingSecret:
    name: keycloak-auth
    keyMapping:
      admin-password: admin-password
      management-password: management-password
ingress:
  enabled: true
  path: /*
  ingressClassName: nginx-01
  hostname: keycloak.k8s.lan
  extraTls:
  - secretName: keycloak-ca #keycloak-tls-certificate
    hosts:
      - keycloak.k8s.lan
  annotations:
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
service:
  type: ClusterIP
keycloakConfigCli:
  enabled: true
  command:
  - java
  - '-jar'
  # - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-17.0.0.jar
  - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-18.0.1.jar
  extraEnvVars:
  - name: IMPORT_FILES_LOCATIONS
    value: /secret/*
  extraVolumeMounts:
  - mountPath: /secret
    name: cfg
    readOnly: true
  extraVolumes:
  - name: cfg
    secret:
      secretName: keycloak-config