apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB4QHsQdm7xWTGG+ZxlWZGiPIgiX8LL6zrz9QrUHonY/gpcnBCZ2UGDPBYZL9LY29/4XW1C1EzQ0bGsnifSxbsIgT44DG+I3+6YWNhpXi76fLHqH/a3gy4QFNnmyxBM7z1G0EmuZAo3OOUvOIpvnqt4+oFAf5WMXTtAdd+Wf00YlpxfkWLG9DqA6jLEZqaDOCTjgo9ce6mHAuJiP9UBx+QsXLZhmULRdND4IYR4bvo5wHLgxWxRxrhUgzKfxQDr3GmHqWwxrtzPeT2ANtk+lqWubmp18q3sDyxLnm0xtM24oDRAv0I9iv1QVZfUco36JUOhjIzLFWQ4SlFi2uDgrRr/u5bDTf4ANEv9OUv5l6d+724X2Egvrf9MEnCeDXCRl5g5/gs/9/WFS6yam3KoT7s2Zc5kO47qcM8LmD4JIoJGvZryKU2Q+gnFFZEIvk3iGhSXfQAQkQ5kSfMixtP7wYqVzn8e4cgt9C4QwfweJlZlXlfumjgBxxa9g8XewQ11HQfTQ5iY3u/Z4cyQdwFg4FW+bXGAFDaZeYSu4wUiQn1NFAx+dqMZ/Ah5qJTMBcC335ZrmPbqP6z1u50ViCM5/VS0Tq7lPYJzajJFd6BVzE6c9gmoEiqaudZxAKjtgEyAF8pwDCrwLHFM5oBq/XWs2+wfa1AZRKmupqmEbgTpzBV63ZJ59fjAU9Z/B5TetzfbyM1sFEsI/VJ5V6pU7UBQt6vjmR4bY3yhnQ+R3rBrnMpirLEb2lK8L5AN
    admin-user: AgABHrMv/IENV7dV6Czl3IPSX35FvNueYuTb6ZluED2mgNNsyoQnmRZvfmgX6jwUPhATf5cIQunRhPWxpLxlxYxe5SL682hgerNN62kpv64XgQzpCPGlmS2LPEI8Pb7ITN0bMS0MJr9UVlLOD6lTyUqNI8hVrOjpmS80OsaoI83Shbvl0pR8ZWLNjls23LzGTg4eoUJhpIEf/e47Y06QNZ9akHNtvI/Ox4dcdokEDM6p0CmKFZfJew/P8EYt+XL+C+ExSJPUXF28TWflql6DVlD/buNaMOcUayEXEdVwcQ3IczKQkmtyBUxyOEYivsZp0uAmaek2KeKkVmxIlsle5+Juq3fCsLR62t+ZKvxa7/NulRdcl/iuZuRTX0rmcgHMNeUXPsndDtsxRaCZv5w12CvgzNlsHCea/IAaM2kV68X3A4omUyHF/wIeMcoSAabuD3W8G3dgrOdUCvOY2544NQdoLXlMWwH9pls0scHVlBCKxYByvAYa/l/4eB7w8HvAZrXPALCxgZsAlANwJsQBSKe5wS+AnTcm65lPydYSBx6Mb1WnVyEOSQHxkeoDMOt80vxY5nglApEidKNSuPwkbv+6ydP3bw388yAaBQUCieMrJ8Mx1NFKxL76Xr83uXqR8PB/oOlKC7yqZ7BJG7rXudL9bfeLVvCY/DZtAdHLSo7rMmedIPLs8bvmmgBMURXj6o6YnnsSHw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
    type: Opaque
