apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAFv7eSBmBUewzgcUU/nUM9OOy5L0uO5YzWWmVg+NW+2E+uyRRs9XElG0+5AErBR369nhaqLmoKyv+jUCVLJkyIamLdgg7bg+PfqMe2sSfjBUWWY8EhRmQf+z/2mJxV9AyBJh5M/M1/ZbTBX5QTEVgcwEZ5z0ZlPCB0EwJghvHDZbbJtqn3ALCIXaeS/6HN4m5UXls5pxJp/qGDGRUVs8PHk9Q2VDzXdj3VVzOSTP6UHXs9Pn1CoC5isPWHrq2eD1jil2geZiMx/9JG+CkGAZUj1u0MFs80Wf5xGMS5goa7S975RGyXHrlvjdkFAd4gUKLrVVqiJaQp9j4iNbq/oiby1rsRz2E9tpr3SJ6k1r+8aXHMQbuy7jswt5us0ASbDe+k/V3hYusn4OAYYLQbGmv5I4fhyPIJ3vyIvBN26JBHOi/Iz+BQzlWwhNbqaF4TRHt7RWUDWkojQQ8+Y5zdDfYUHLpQkmZGIFR1Q6HtbC7pLsIp+sxuDqCCyC7E/tYhEHJx1ycMl0eMlDFJQKWyGsCGzqUQv3psrV2C8Qo//mqVIGQJuG/WYMa/Y6QA5SsNGA72NDUNxlMa5UD9PEweW8MRJ1cp2DBlhWaJz9setz70zB91p+x9i7HSzccYmdSjEAbEd8fpzCnTU5tpQr2nqmk1qUnNl/OabNW/rBBMJzUDaErCUg6ejZ/JWOzllbyS8bw4zEz1GSHn+fI7I8zjvNPNR4g+26pXpeZmi8e5tF1IcEkHo4NEGpoI
    admin-user: AgCQIBt3xg/4zKBdw2LaHyM8eY0afWzV1TXyoxRD/9zqI5YJiISvJYz7Dr3hlXz2TyxoLKb5iEpeeyahdEnO7MFjJb4xmVtUp8Pv4eaAd/CbXx/c7khgFfgMoLsrlJU47DgnLpUc4ZSGibcFyZEEy08G0ZS9QY0nY6IAmcs1r4iXZdX0JhULS3oRxoDh9U9DTwQJL6/hIFgVxPwZKKb9VzXw10ITC/SNnq9gHTW78sh9igWKOnYAS80qQQJo16weF/bz3/g7N+vdZaGxuEw0I756gEoxJdsfHVEav5P1aCIPGkz8nmXLaElfiJbyfgRdiHV/a8oyMevHv0Vlro+jJnFyBYajTjnNjnaIMKGiPIJ7VF+yAx2kzYlGQN6afn5ovz3rfW7KZ0X9fb7NQC/NDKgAeZNujHGM0IfAAy8hcrf/IFktjLurLe/n4LjcnKkZjPoPsnGbuPlKI2Cl39E96TcxVP1mEe8ykUeWC+J8xNyK+m0AuzuFP/dtDCHQvtRM2LsbVrTGRIFCwTmA6IDwB3yiQ3XC+g86XhkPvzliAXpgOuX6R1FHZjC00ehb64xEO6FPuaZRpaqsV6hocjCso2VOaBl4FH+t8EJvUo5g5225Z2xA2d98jwc8rlQl+1owoPRdywxXLE0u4lZXs9n5pHq6fjHJ9BZhonsDeAkpofZyQFwVyZGYFwcuQPyRZLSFXkkvje4PXQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
    type: Opaque
