apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAMDaug96TnThFF7qNZE8ENPbi7mBgOciTrEANuTfPZCfCeDH7QrjplHkhSoLe6xlfuwGSGLF6gAy4zj+hps+a1RRgJhTlZ8hMBN/hLwkOPEn5AR9fXoj0ugWB8HKhrkDDfoRK9aKmZp4sFafPJnUY2kucrtkG3DE0kP3y+uQxV5Bm07t8uYq4KmTqqog8StDqm1WCkpUvStuFN5wm+5fF/DS2O7lPgHxjhNqPhtTrtBs4KY9Rh/7359YMqTEHy9MD+2Igeock6poN/9CaW4GFdMc9DamCNnTSyL6isoy/IYK2wLahgfo6XSHoabhdmhJuGcSr0cqjAr9IeBfMqR7gPkUwu/dv/v0aExEN5InltmeYbuCQBFimkU10WdSuK5ToBP6sgLIVK35gG+sE+Eb1jMhJSbhjeY1FWM0SapjGECgIxVKIUsmSim92oz5WJLgXSMayOteYG03pfymhclMPeqFGmC05iIRp3JkkO2v6UbQVVmgthfMYOyDsoBE1kh5jQBYPZK6D/oc0GbO2urazeEhW/yu3EVx7pH4zFm7bHHIodotODKu/8aAnrD5J3a1SZXoT29UnQomdflhU8k6oiFPlqJJSlDAN79XpeLWhghwg3MY61dWEjh0dhJ0Z08o34nRwF1246fgIxswna1xRkqkk7yhJaWgm7dKTWoAqJn7s9NqxTcql9q5m8KvEsdXEGZf0N+sWhD9NwpafYpnNe0Xlteax/smKajYsYPnSQFKTddE6K+0y7
    admin-user: AgB69I09OiTg4KKpxytvm4KQrX9V+C7/i5aZKWHCsHPlozbvVJHZVAeLFjbuz3MXbP5pU7renP5JUU56UysSM0g+rSUM2DqMFHng2+272ejLg78eBd40GFK5PxoFKjQ/7ved5CBD67hjh94LKqUCy1eKOzNvG4SEP4S9whslccBLu+FPEtlrGNfrrdqpJiUDxwnAyPfvdLBfmzrFcraWgPbz2QAfMRF1EkCY3Zpvf/mAIVlIQ7axQA6NOF4wO17bSWDZ9yxTipku0Guox3tep/wpmmxTlUE4P8LqeFPwVu2jcu3sD6dMgYZ+P8NIrBwEO45hdb5bQnJmMu/5Ac1DXxnV0tCndNbTgt0jEI5UhM0gYONyeszbXTT5msakESya3mU3E3KcJ5pEbIIF2eZ7fDtFaZdXBiCDUNqj9NVu6HB0k4nq8ZQki/we/4y6IooJca0APy6UTHVewSGqRUMYzNbQRbj3Wb0WGnYdrXucqfHSWVP6xpUE9KNZD2l+efD4b98N/19MOt1LC1NYMWJRN3+gN+pHxIYnMjTAdq0KBBfMVjMHAQ0fdVeQ/++l08vL8FYIIlH/2N41unQUqxhZ/7aWjBMEPskwcTYR/WHn8H1exPATX8h0dXAKkEhYd3umFWoyxHN1hG4sJYIeUO0bCeiNKhm9Zhe++zP11Us5zU0czOXL0Fc57StuXZTaaZFTEjDiVCFwpQ==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
    type: Opaque
