apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../../base
- secrets.yaml
generators:
- ../../base/helm-generator.yaml
# env merge issue, remove patchesStrategicMerge
# patchesStrategicMerge:
# - deployment-patch.yaml
patches:
  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: add
        path: "/spec/template/spec/containers/0/env/-"
        value:
          name: HELM_CACHE_HOME
          value: /home/argocd/.cache/helm