apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- ../../base
- secrets.yaml
generators:
- ../../base/helm-generator.yaml
# env merge issue, remove patchesStrategicMerge
# patchesStrategicMerge:
# - deployment-patch.yaml
