apiVersion: builtin
kind: AnnotationsTransformer
metadata:
  name: notImportantHere
annotations:
  argocd.argoproj.io/sync-options: Replace=true
fieldSpecs:
- kind: Service
  path: metadata/annotations
  create: true