apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: promtail-helm-chart
name: &name promtail
version: v4.2.0
repo: https://grafana.github.io/helm-charts
releaseName: *name
namespace: promtail
includeCRDs: false
valuesFile: values.yaml
valuesMerge: override                 # merge, override or replace
valuesInline:
  config:
    lokiAddress: http://loki-distributed-gateway.loki.svc.cluster.local/loki/api/v1/push
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
