apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
generators:
- ../../base/helm-generator.yaml
resources:
- ../../base
- secrets.yaml

# patches                   https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patches/
# patchesJson6902           https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesjson6902/
# patchesStrategicMerge     https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesstrategicmerge/

# kustomize --stack-trace --enable-alpha-plugins --enable-helm --load-restrictor LoadRestrictionsNone build cluster-addons/kube-prometheus-stack/overlays/kind-prod | yq -ojson | jq -s | jq '.[] | select(.kind == "Ingress")' | jq -s | yq e -P

# transformers:
# - ../../base/patch-ingress.yaml

# patchesJson6902:
# - patch: |-
#     - op: add
#       path: /metadata/annotations/helm.sh~1hook-weight
#       value: "5"
#   target:
#     kind: Ingress
#     name: .*