apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgC4yDbMa5T1IdeNEWB2/aX1Xtk7s1oU8Jv/hH4S+fLQefLXVfdymJOZ+kyldj0co7CLdTrS2NuOVJDOu0xhABWshFGyFAvAKeZHaH9JVU3IET5MeZnM5tR1POP1k+bp2wgWm7Sup2XEgz0YUZEk1MWBGmGrVWoiaLfo9FZqBexCyIebcyAhZKfdq9jnYa4IgiKGWgbT6jWZVCSyADWeKD1I1khdyZMu14hR1bmr3xq7IrGY0GsPuMBQ4u3m2z5JZ5CWW/ROqWhplVsQCPO5cukmb1MnAX6bi4h7JNT35RVs5EW2Op8h7J7VAPTvvyjjI1XEPUNhSuemn69PeqoIXWTJyYScSLGstxj7NlZ5yGKoczYl4QXqYRTZ+o8x3ATuE0iKx2JTvOO6PCCFnSOu3i3A2fsBjT/p8tKtvuMjCkH1mM5+V1n5Ms3aRiPy8a4F46uBqXJs16G9lzWNYV1+JHqTv3Oofg5ZABm/GLEWDiN5g9xhfWzne09fxz+mC0BhAUl3jYvJZ3GaCDZQgvOgi7Ym7wl033WDzC88S8JQepiK8DkfXkoiYtUmWz1KWabNxbeklSLaRnoKZ8R0y5432LlwH6VbMxzFdL1pW2cjjq+Sh5WG8e/2S1u9fpAWtqwZNbEmFpomZxPrNHpgL0Ah9B+2nErwc9JJSBsiFLX1uLeC7AZMkGwcT1fwer2T91Jpl1TqOpyj3g==
    admin-user: AgBirWe/Cf64j1fma/8zOc0fhYYsvXfkOaoyahoG4cH6/9fmdA+5BeHxw8+K2icSHVHc0TfX8fn2oFGPeIfLdntWmTgFppAtHM5YqkOMU2RLQkcCJqRkDSUpJh/WaRFjeGxzCgrza4dqbxoD/vcY3O1hksxQGYm23Vf4G1HccafIs8L4JOdDcm1ZRxv9vpfauQE4Xhzt9Qbwl7kiaNfBAOVv/qTrSkCLXlCf5vjane0uOgbb5dZ/YT6YhRKptngwGDO5g1BRcOey5JVJL0p2Q6fxbEKl8obM0erfQ+FWfINuiGEka+e3Ok5D1Hcus5AQ73/OVNcWN0+R6aEC4vrhmNxdn48wbzQ+4FR/PCoE5a3dFF13ainzcM6heiKWMQSLqeP2K7VRRDiUPcEZTY7XfOYkt850YDOexCE/6G+f0QTE5nkU91grB4WRzdV7wi93Np68uYU65P4j7g+fX4SkQP1NzTKScz9g0fNV3/Crp2zLDAPT2Han8KsjXE9i+Ud4TthAbQXHrqPEDZvhgLEDAtaaYBwUSe9tqSp8DqQ3MpOPo4z+WOyy9M8RVRU/tcT3IOM79JYeVwZ9py6ZbThVacnjOR1sI7RPmUfKFYTXvzmPxHp9dMmszQ/RQtWHXuoC8zvFcFG7aKYNy3pp/C8tHBHw6sCItduyusRgutqj1M3z8RdnmY60OZ7YidvsTgpxXjVoQhHzfA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring