apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBxwiSeI5VjOc7nFa61kPxV1XDpYuieADmQQdJlsJW3tA1D+eyz0kvX8nWL2HIe/2LJip+autqyIUgCLPP4ryYZxN5h1K2FWi3PKma62TcjsxsuW6hhjqk0n+kr2F0wGBc8yhFexSklAAtbvpKJnG8fF+nzK6iwGxo4W51bqW2u18Hn54ip2EYL6N5wSSIf0CvPub4yk+RZVGoZ5vA39ww3GN0XH7Qxfat/mx/uCIL+cG9U+ba/qe3fNwGDICuSmajPANFL2ns5YAUwsP97jG/+xy24FEjyZO5jqzmzFs5Ik+gN8vEW0CiVE/y7lno8HoZm+RMcAl2oDEQwJZ/fHsuX2cWrGwuBKsPcSmPG98Bi+4OKHYczpoa2itPxFHzB1CnOU0qMQTT2LRJrkiPcRAtW6flW6DXLykXT138niFq6oJHXDXJ5W3P6SP0yewbzOLSWnGfzzUrjqyS7sx16TZ4O8xstoboJRkNOqDxaMg7bUMWEG92j/66T+KNINgMLAnuhkgdS80CILdCwPOJC154619Cl/so85Cg+KEIfI0f7yVnDV3YGMkmAFULK+X0TODWgR3QXltGryPjESuQWlsVli/sfGu2dd7PNkPJ7E8Fp751H82zddUWG5zgpeZdqgxggqEoz5iPnvXudyyDWeZPnmv2m5S00ysemjOfEvJ3Le5s82umkYj1RnMNqNezfdIL/FGe29g==
    admin-user: AgBYG7xbpPUYm6wSTlIZTLl4Xwr96ua5nvm91QsUIrNRrETiLFzs8eSFQcivFMyCNCE4/G5pRq/0va9+Yp5Y2lsuSrKNHC/sprwn4exr8/l3dxciiy/vNhBmPYG+wVilF0DX/ZPsKfs9LbBs3KkZ3Yn6qqInyZHZJ9RfGqCvQsMubWskNqrg56aOP9ofzrQlPOpuXTDnUnCpVhsUf8doRagxQzwfMx9oAq50fwQXv3rJiUM99iqkQnntTeZcofdmHFajjo6aSLGOmtWF1odhPXADasQld8GZWN7jcCpbkQC8OToP3qeoqoKzONYVgQeQWXUZLDnZ8+GyCFrh98/gRs79Ty75J9WMzJmXwdd/OIcK8MeYod75Iy+BpZCgfx6R8H0/BI2hLh9F6N25DajrVP4tEb8cPrJ0nAP6yB1zKLlqOZUXaNnGYhIQndvhV72mXtvof8NjMp/CTEimjDzDNgNGiiiko35HaQ7zHycwKc/CzB0AN86mT8rLqII9soEvGMlhfyb94mDoMZlrOVhG8Z9+YQuEF/wlF15UM6HXeVO/HEPYDDerrFYa4pdE6PqgURZb/4h5BoNXmE7556euaSMXRprQsy7bLoUMCzgbPsedZljflLkXbbqJDbfWT4kgs/YZUak+ZyIEmkhdI6zFsjSwTBlIuAqN4Q/ap51FlRk0DdErJRUfgIF9k/qtbwVivA8EjaSggQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
    type: Opaque

