apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB4rYco3W0Y6K0I3iLtcg7zXN29aa6MA054bG6jKGEFbRuwS69RlX3b1d5KCVDG25L91N9Ldehe7yh6pkjVOsyZNQX2zUWlAIjwD55jwPDd0kR91sGQRRp7BDoU/C36K3Hzj8Wlim0L2tZIpRxECYOy7nWJ0bHJYZ0dVGAuO0arQW4y8o/Rnjvs0MNs4tLumhHiNA73E5RlxT3GO/IIGPWmTo50EdJ2RFG/lSBZIQrF1xr/v0ONhdITaWSQZNLzNtCwmEfqq4xBbxRCQcAuxgK7imPaEY1h7TEEEusrN3NclYH0Eay7XqlfDEbgfJsrwCnb2JltnMg+e2z6HYppj+SkOMpRZIp3IEJwHrInxiRaMS8jGDFRr4toNCAD6Uc5K+nrr7J9FAwORes+6dsbmGvRIWghb/0MqEFdQj+fWqYCY5+XcWleaCzPVg63H1r97zrsw8SUlPWs82UiHiNzF7e8n6NJvWIC/ToLv5R8U0qKgN8HNnYy7b967D10sGUcOXFzurs70jHf6NntK5Sj/dEjyhz9Qq6NeeuWKXkHU4rW7YVQLBHW3kYLL4qrNe+7TBIsH29T7gImWIsy0lFv3nXN+8xp3FHyRH8UF2KfusxdhSh0AvUL9azZCR+y5QkF0Sxvo35JszP+NaN2mcbtZmJyQuMyT9fcgoxgwLdbb2K7V7D0mw2upYq8QdY+Z6sdSE+pKoNMTg==
    admin-user: AgAr5t40OGi1Obr7lYn3Ph9o8DRhs+8zVLGWR3z7lWjZR52Hs65r7eMdNK/yKJX1qwpfQNuj2rqmEsAeZqvJUaOM+tVjdFjVmrA3GbpYicPmtyfQplz77hr6moXfvbedVmLfwQqzK5aQ3CWa2+DrrFTkKdsKGzgdIBnoXcbVPrFq7QWRPl5FPw/0ACuNReCSNKCypXHANpl4aWPCSWH6t7REeFgAF5ydUiDZyQpl9BOtuYOUwLYLYulo0ViKyjKH+IV+EchCGfalHHjgQL/NF7I/B61Irs61Lo4gKenqTPiSGQnheEQEEStFxvcQAqlCnuiHsWLfYRfl3yokqRZXZq/erjPpaLJI3FTzb/nTxesmaxrV1QExph1NKJH+KIgOrPxC1iSPdZwt1a42eXjeUCH7KwecgzSPb6R8rZhB/L4Et6DJtnFyXbjuLwk6PJ/4OPMPY2yr1bGs5xDBgva9eDvA+PmRauyuDU9DZ1UFcL/sVYIwp2Aiidk1PQgRTygd1INA7bpIXABZpWENZEkvkw2WiTZhJKnPm0umGVLOUOs+MCNME+UZdz7z3W0tVYMbh1QVes8nZhOuFObsit/3oGiQru2wTgNaCL2U2jc/hy0DYwtuBpKChMVOnvIwFH8gUze/Yxg/SD2N2ySh/qW7v9nBiKfLFuqhG5kLC7Xd9ApedxlhBSmJNiCNxhzs+Ft9udq6KZrILQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
    type: Opaque

