apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBIYlToTeaz9vcXL+cQTRm/YrDL0YZN2fSUqB6jLyRIEAoywVPUn4lNTj2eHUjWxxsfXng3MgYbanadlMiJKuIyJMijj6H5hbQf/WnLKPh09GOykguxAB+yKf7/XSDyrDaM5/A6RlFyJm+cxPyvrkrmDmPhGQi7p1aatulB3kK8x6/1Wrzj83C2bazmIMVhYrNvaEjPWIX2ZD8c+rm8pyTdakaMktTNhXTC2/X7gBanYjGlceAdo/fJ2peqUBhqf8J7ZrJXBEFyNDxusVu0vIvP1MmuRaQRDeS0U5Tblft17HOJ3h/HSrDICmONh7J829iBg/H+geZml8of/XOEVrra278qlcVGQT/ZhgUHE9e0q6t4MIiWo4JsbrzEaIO3s2i3SPah4LXVUNiAp9bO1WLh9qAeXuiDoK+d+4RiWuF2/zh6p6KSm0E/PoEM4juORHzJb5X9EhBRfXFIpN1dd27XV9UvFrzAvXDE/2Jo5A7NWEF1qAxRdtUvBpnIHWVkVh5t0XEOSRGllJCrXoEHDQ4t2+zY28qu6bCPt2NYlkJeHkJj3w1enWXDDChAs5di2wlQosLyRMqTomeO2qtGPDDf3gqUCLYhFbXUZBtMhxOY063b9bkLcK9wmEjfUUePE5BXrLpxIo4IiOFIabE1QjTrO2I8jv0rcG59Q6iZ+BAonu1xe/yNLajsJBqj63nM/KQEubVVIQ==
    admin-user: AgC+WgMmlR4Fq0dw1GhF0jvJO9AiR03bik8Xij8OzZeWAw8iDXdeANiLFj2RW3o8PaM+GK9myeZActjNM641jw1sdJYfbT+IhRi/of/TZ1E8YDtddFUWHLT+/TJF3gCEw5+/EpJaapV/8Vv0IAmK9byRuOMtn7mmsvIwmnz0pEGuKW6sxmvzyXnJceKDCycmgoTjg33Zwd9smxsdkbb7dTO1F+tvyh+yII/b3F9y4cjqu5oMTY2tCgecwljqXTgZs0TGuwOm6lGQNeDtDVg8qWRtjqa/Mie2C8ExsXsxHf9C6UjsuoxZmFMQku0aM7wfTfqlX7Fx4scqO1e/tevAnMTXouc404mYG64G+QucBUJk2K4GYfdgaRtMJirLCSxC4O50GIn+K4xpAb0bYjsHj6OiZfIruk+BMP6B0WkG0ivRdT5azhitZ0465ILRHxyPnUsfTa6K571ZrqCEl65nohbt+ea+M2jMD/Fn1ngpnS7QiuPuZ520R3RLJ4hDwZiP5VphT5XKbo7yoCZHUlycyZ5RvAuzNJwCn80+lq9nmWVJ72zQ8XIArPCIyuUGvjccROQllwgZIr27HCMeiWkh9x22RQzYnuhPi7bYZPappYqwA5uBWwqzmGzy/auwoOTWlhH4znUnCzBwrdSO2TiyZZA41gJKiI97EgeqL27vwAZwhLIWLJkL7sqrNQTNGyrnNgdAP6sU1w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
    type: Opaque

