apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDQgyo/EZsoFK4C+I8CCarZebATmgCrDpqRY9SMst9MrYM2+dVJNFTVv8nhToprybhLxmtkbopnZsCHQB392eLEKWzcOVqAQU9BDnAV1/GcoI3xJcwUQZlHKw8YMCVZIk/0sKwNzz3s1BJTiAR4P6HfL1d5NeaMTqnzPGTKidSXj+GeZxkEplNK5Iiw/uP+ZYA+aJeE+UEMJR2HwesKKtUpEYOE1lJBK+0tdj8UQwa7gf2mRAjkKLBzTmrtu9bx25HT3ds6li5R8dRoH6udEC2o+uD8YyLpd3k9X54HO0ylUpghdooLihjyNY5lHgi3tpS+NtUEXbmUrdT4E2wX2ULuhzQe6xvN1bmjuYA08Y0P3FaFp9gbBiikAIei8ybWZEF/u6iIDHlNgEsZlgVp4s/VPFrb56oRe88yWO2PjTEBygP0nsf4aYRlV3j+iclKr98nkUxso46P+vjFVcxv6XvW8LaHhl6i4XKC8yORispERIsikjn1AIASVtkVEtgeVj2KUQNdbtIQ+TK8gB1Ag/i2f58g6dUYYYbrBpe0U8FzXC9CBK8JT0TEwI11TFpltfbspWwlPABhlN/FdATqSKbdif8asMPgmM4astjmQti7Q/jx9ooxo6i6bCxyQ1nFViLMnkGaElsSn+HFlZsAiJuYxkymeF7C0TNST65j6PTLdGXrZv36/CBmRBqDUjRlmpCCn2mP0A==
    admin-user: AgDzQFc7nSrf93RSIR4Jrw62cffGRCkEmgZt8IL9m9DXhindctJBCa3LGvnNlyshbWdF8W1OnnoGKd6v0DEC6thmkR/aNxtt8CA4MkapPtlZLJXXto+ZR9coDBe2fjLpfs3iFItLHGg7/4jdDCe/5w8WFIbKpl+71VVwfy3OauqgLMAN7Ej2n1d2uWO1ewecVp5jI3ZG045spNbRwtHdSxGX8brDhl17jP1RVffbn/NtnQ9k4kzmsdyo31tWli+ItRNbdcSYgQP95cF92is+YF0OSSRHCBcKk5ChxgbcPmQDVWGUiBw7bwzCn7Ex/niyP7Hw42zrapW1rAl+bISw8+cTGHfZmchRKWaEdJAl/Xn/HfveO/GK2mSdrfpSiMez2d/sMrmjmr1CKPEDjhgFeeeagmORynL4jWBPJYITx9UNSCsyd0Jp/bCkHaX1ILVFc+Ons6INYSyunw9S3pjfUlKLMQ3gbUO8KKB5PctO4TcBdrj2EKSkyp0jtqIaphBUMpzOSDHx4/2ZQj1xj4MDiuA0sCjFx5hJ0xWWjm2vKL9Th1q967917rJHTffLHXGR5ASnr89F+Rmq6h2TMfr/JHk7ypNZrjN50pfVS0Vp3uoDTgWMVwKJAbbtB43OpwNWUA5fI9vbuVrtTxSP8fHSq7Mr33llo1wsu/sOWepwzFnu6tHRMhMbSlfkZveNWyiWTunBq2O0uw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
    type: Opaque

