# https://artifacthub.io/packages/helm/bitnami/external-dns                                                        # https://artifacthub.io/packages/helm/external-dns/external-dns
# https://github.com/bitnami/charts/blob/main/bitnami/external-dns/values.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: helm-chart-external-dns
name: &name external-dns
version: 6.38.0
repo: https://charts.bitnami.com/bitnami
releaseName: *name
namespace: external-dns
includeCRDs: false
valuesFile: values-external-dns.yaml
valuesMerge: override                 # merge, override or replace
valuesInline:
  ## @param policy Modify how DNS records are synchronized between sources and providers (options: sync, upsert-only )
  ##
  policy: sync
  ## @param registry Registry method to use (options: txt, aws-sd, noop)
  ## ref: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/proposal/registry.md
  ##
  # registry: txt
  ## @param sources [array] K8s resources type to be observed for new DNS entries by ExternalDNS
  ##
  sources:
    # - crd
    - service
    # - ingress
    # - contour-httpproxy
  ## AWS configuration to be set via arguments/env. variables
  ##
  aws:
    ## @param aws.zoneType When using the AWS provider, filter for zones of this type (optional, options: public, private)
    ##
    zoneType: public
  ## ServiceAccount parameters
  ## https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
  ##
  serviceAccount:
    ## @param serviceAccount.name ServiceAccount to use. A name is generated using the external-dns.fullname template if it is not set
    ##
    name: external-dns
  replicaCount: 2