apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
  # namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  strategy:
    rollingUpdate: null
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  strategy:
    rollingUpdate: null
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-notifications
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  strategy:
    rollingUpdate: null
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  strategy:
    rollingUpdate: null
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  strategy:
    rollingUpdate: null
    type: Recreate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  strategy:
    rollingUpdate: null
    type: Recreate