notifications:
  argocdUrl: https://argocd.admin.plato-devncoargo.dev-sbr.com
  enabled: false
server:
  volumeMounts:
     - name: certificate
       mountPath: /etc/ssl/certs/ca.crt # your self-signed CA part inside the secret 
       subPath: ca.crt
     - name: certificate
       mountPath: /etc/ssl/certs/tls.crt
       subPath: tls.crt
  volumes:
     - name: certificate
       secret:
         secretName: keycloak-ca
         defaultMode: 420
  ingress:
    enabled: true
    ingressClassName: ingress-nginx-admin
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - argocd.admin.plato-devncoargo.dev-sbr.com
    tls:
    - secretName: argocd-tls-certificate
      hosts:
      - argocd.admin.plato-devncoargo.dev-sbr.com
  config:
    url: https://argocd.admin.plato-devncoargo.dev-sbr.com
    # https://github.com/argoproj/argo-cd/issues/4344#issuecomment-890382825
    # https://github.com/argoproj/argo-cd/issues/1171
    # https://argo-cd.readthedocs.io/en/stable/user-guide/private-repositories/#self-signed-untrusted-tls-certificates
    # https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/
    # https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/user-management/keycloak.md
    oidc.config: |
      name: Keycloak
      issuer: https://keycloak-01.admin.plato-devncoargo.dev-sbr.com/realms/master
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]
  rbacConfig:
    policy.csv: |
      g, ArgoCDAdmins, role:admin
      g, ArgoCDViewer, role:readonly
    policy.default: role:readonly
configs:
  secret:
    # -- Create the argocd-secret
    createSecret: false