apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: helm-chart-ingress-nginx-public
name: ingress-nginx
version:  4.2.5
repo: https://kubernetes.github.io/ingress-nginx
releaseName: ingress-nginx-public
namespace: ingress-nginx
includeCRDs: false
valuesFile: values-ingress-nginx-public.yaml
valuesMerge: override                                                               # merge, override or replace
valuesInline:
  controller:
    ingressClassResource:
      name: ingress-nginx-public
      controllerValue: k8s.io/ingress-nginx-public
    ingressClassByName: true
    ingressClass: ingress-nginx-public
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack