# https://artifacthub.io/packages/helm/kyverno/kyverno
# https://github.com/kyverno/kyverno/tree/kyverno-chart-v2.5.0/charts/kyverno
# https://github.com/kyverno/kyverno/tree/kyverno-chart-v2.5.0/charts/kyverno/values.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kyverno-helm-chart
name: &name kyverno
version: v2.5.1
repo: https://kyverno.github.io/kyverno
releaseName: *name
namespace: kyverno
includeCRDs: false
valuesFile: values.yaml
valuesMerge: override                 # merge, override or replace
valuesInline:
  installCRDs: false
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack