apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBZy6I2+DfPw6lhmfGrmNkrYwDGr2hjIzMmVflaDuzzdv7ZdMGOxHeRY7Jv7GdAREeLmCszfgpzfJ3ZPlC7pbIGsu3mPJqYHlFQ2AG1mr8owgGWGqI4gFcdG71ghFqkxXO+RZPsRjSxnlqCrlL9g62um5OdpwoJKOWKiHbkP4USNeFOB1WlF9zzWNKGY4typuQaFGKvlTzIG9LNx7nqW0RLzaENGYNAHqswyzkdxZmRdvt3SQfrE96eG2WFeomN5Vk3Z0UMwUhS+NhKSgdt5diwDQq3EstMgk3vxjf7ug7rD9qQpMv+poDDF8ICng88APfjcN5Aq5X8BxAZvt6RxsN/y4WdOY34/KhZymGVGk8bC8tSDxtNHJGMAgzue4Vw2bCLeLu5di2wvYG37jo72FjjIGy8EvN3qF73TaYkW1nFlYLlZ6WwPPaV4FlLb/0m4wo/jilQ+x7SFn7WvoSy2dYZGPC6Ae6cd1Mexlpjs0r5SL1AX6dTjJakkfSNFk4gqB73hoxs+577W9STeMONO6e/Dei+3T5m9txAqZd3R1B2lOzhtaBoIgYFQ40G12teu/x2ouIHWiBJtjz27rQBgr6ZbRr4kcys0BiqY77j7YJcSW00t/B4w73GNuFscXw+dbErS4cTWAPebcML0gTlPFKds6sPHjrXPYlF9Sii+WVx7cVwpfMTf2gNwj8W740yQqjfjFw8JQ==
    admin-user: AgBBQCAfLjwdiYBiYNWgdXeuFuwsxX2EbU4WkVwnaa7YkVPBbfZfAeBG1A5i/ydHsXBQDItSFLxm2UVT1/JrTy0IthUqyzVYyEVDdW0kYu/tDNTAWq9IHY9LCYP2IluQ9ImVGAfg0DEAg+74dcdTc7S4fEZxopS3nxwBSeV5SP+8nQoGtM2WwztSZQsGk1OgTUXoy/i2gHkOBSMRFOMm6UJkPYTfR8WF6hlv8OYbKnQmbjxfEHpreJsR/54yQXu13+kIExFj7VcElm2Idl0KmruO+rBZaCUqYPtddZzckaBNc+r0ZrQKfjDxpP+Xd194r16GTxkTR5JmD3q3pcJZ3MZPxDK5CveGm9DZjqfreR4Iaosa4GXZVuKdwVZnVV582T1qV3HLlYIXMQRGSA+kcWhx385YzrIM2jyedNmD+OFuvkQEXhLM+ktF/gQq/DMZmz2BOf++PJcmZU9TqqR01iBmsNptgkw0vLvTMHiQJHaIPTlndUeZgkaeM7Sc0s3rgyMSkfTaOPk1UG8XZw3CelI7vghgi42huukrm+i8zsawYglN1GGkgNxzK3pcxFNniLEc5qdAWQnP1YZFHbsJOYZhHdnhbhaLMoGmTci7W+pWdzKcEL9xuPwXcHrdooz2SXTz3FYHj1brNC/kd5Bg1LTSVErWzrNUiwcTg0mJ0L/4OpJA8EfRT7bjP+PYEmPr2CD7M4RCXA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: monitoring
    type: Opaque
