alertmanager:
  ingress:
    enabled: false
    ingressClassName: ingress-nginx-admin
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - alertmanager.admin.devncoargo.dev-sbr.com
    pathType: Prefix
    tls:
    - secretName: alertmanager-tls-certificate
      hosts:
      - alertmanager.admin.devncoargo.dev-sbr.com
grafana:
  # https://grafana.com/docs/grafana/latest/administration/configuration/
  grafana.ini:
    server:
      root_url: https://grafana.admin.devncoargo.dev-sbr.com
    # https://grafana.com/docs/grafana/next/setup-grafana/configure-security/configure-authentication/generic-oauth/
    auth.generic_oauth:
      enabled: false
      name: Keycloak
      allow_sign_up: "true"
      scopes: profile,email,groups
      client_id: grafana
      client_secret: iagsmFWVLS5DcEoP9SgGCE3OFAG4g5VF
      auth_url:   https://keycloak.admin.devncoargo.dev-sbr.com/realms/master/protocol/openid-connect/auth
      token_url:  https://keycloak.admin.devncoargo.dev-sbr.com/realms/master/protocol/openid-connect/token
      api_url:    https://keycloak.admin.devncoargo.dev-sbr.com/realms/master/protocol/openid-connect/userinfo
      role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-dev') && 'Editor' || 'Viewer'
      tls_skip_verify_insecure: "true"
  admin:
    existingSecret: grafana-secret
  persistence:
    size: 256Mi
  ingress:
    enabled: true
    ingressClassName: ingress-nginx-admin
    annotations:
      kubernetes.io/tls-acme: "true"
      # nginx.ingress.kubernetes.io/ssl-redirect: "false"
      # kubernetes.io/ingress.class: ingress-nginx-admin # can not be set when the class field is also set.
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-passthrough: "true"
      # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
      # nginx.ingress.kubernetes.io/whitelist-source-range: ""
      # https://loft.sh/blog/kubernetes-nginx-ingress-10-useful-configuration-options/
      nginx.ingress.kubernetes.io/enable-access-log: "true"
      nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    hosts:
    - grafana.admin.devncoargo.dev-sbr.com
    pathType: Prefix
    tls:
    - secretName: grafana-tls-certificate
      hosts:
      - grafana.admin.devncoargo.dev-sbr.com
prometheus:
  ingress:
    enabled: false
    ingressClassName: ingress-nginx-admin
    annotations:
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    hosts:
    - prometheus.admin.devncoargo.dev-sbr.com
    pathType: Prefix
    tls:
    - secretName: prometheus-tls-certificate
      hosts:
      - prometheus.admin.devncoargo.dev-sbr.com
  prometheusSpec:
    retention: 1d
    retentionSize: 1GB
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
