apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: trivy-system
generators:
- ../../base/helm-generator.yaml
resources:
- ../../base
patchesStrategicMerge:
- deployment-patch.yaml