apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cert-manager-helm-chart
name: &name cert-manager
version: v1.6.1 #v1.8.0
repo: https://charts.jetstack.io
releaseName: *name
namespace: *name
includeCRDs: false
valuesFile: values.yaml
valuesMerge: override                 # merge, override or replace
valuesInline:
  fullnameOverride: cert-manager
  installCRDs: false
  securityContext:
    runAsNonRoot: true
    fsGroup: 1000
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
  ingressShim:
    defaultIssuerKind: ClusterIssuer
    defaultIssuerGroup: cert-manager.io
  prometheus:
    enabled: true
    servicemonitor:
      # enabled: true
      labels:
        release: kube-prometheus-stack
  webhook:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
  cainjector:
    enabled: false
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
  startupapicheck:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true