apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
- namespace.yaml
- https://github.com/cert-manager/cert-manager/releases/download/v1.6.1/cert-manager.crds.yaml
- selfsigned-cluster-issuer.yaml