# https://artifacthub.io/packages/helm/bitnami/keycloak
# https://www.keycloak.org/
# https://github.com/keycloak/keycloak
# https://github.com/bitnami/bitnami-docker-keycloak
# https://github.com/bitnami/charts/tree/master/bitnami/keycloak
# https://github.com/bitnami/charts/blob/master/bitnami/keycloak/values.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: keycloak-helm-chart
name: &name keycloak
version: 9.6.0
repo: https://charts.bitnami.com/bitnami
releaseName: *name
namespace: keycloak
includeCRDs: false
valuesFile: values.yaml
valuesMerge: override                 # merge, override or replace
valuesInline: {}
