apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bucket-s3
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgB5V5Qe6hanjsJ1X2SXlI4SQwsi0bKcDaTRXrojBeGNGJTtpqepSY2fI0TltUNDpIYyyVtudiwHl+HfFBiHyOl3MaYLZMQZUFT6AhWvJ+6Rdh2qVYNX6gYwKad4RHIxfZMdX7TEpsTpNLtP3naJaqR2w9XDZAM9ACW0oLhULTGW8mStzrjF6QXZVxcTZP8w0Qau3DB9zMyB2UBhNTV4QMdlSj9YaMuSiqFai4JvUHPJYzUU5VEoDJvAlDTm74v1iEEpRkySDGLlnoZIt8b+03dfWWjDu34bsZbObrVdJ+0efMbYUKNi1csxMJcMlLd9URTrZfHyv8PSyY9YEdob58HHs/A4hIN4nVkG7qwgzddjzmeojx8I2jIRHMaJyLrvryy1n+hFce6Nbna1tAxYhtp04Ck+6hng5au/xvMOfJSogRQ8pGeIoDetRjQdtKJEEOxoz+qe548lw3p1XvVq9lRwJuLaFMrtYt5YoVh3Pdk6ARMH58uDfXCcNJCVT4fvJWYRmb9jqcESvFBUwi7e2+52GThS4Xey39Gwqslg6ojo6Em3RgJJIw8Kluid7O9qEog49Y84lra2kiQWQwU6nvqX0dgtJn1Jt8jLXvOVnHevpKY8wfgweZt7t2BYWHqeV703wNfitu8Y6Gj3aJBzjvzIQGWWr/nU9pWRyOVxfofxl4nT84pnJSYAAvkQ7ejWX+416gINKpDRGRi4rpVywissSBVqUSn4ifcER5JT2Emwt3/o6jlEzh4I
    rootUser: AgA8SgcZsBZT7bTfLA5yCKpEU2GdGYAMU3uZLZFdvRFCKcHln77DV2VP+YUS/OXyTZpN+tzpBSwwGAYa3XHnUc4ydl+2rbEquQIsjFsx0qLJCHkugo4blzSScKkxAnR287GDBqdM8q5e1wmovsmQ586G6aaH2s1HKu9Oef1oRNfsuxWtachF1x6Ar7K+hFRiUoUFe5sEGmZzo8DugmKtn3oq6WemS7DWISTpkwJjOSZofV+OyPTJ6fStx2nQorp609Lfv+gtKDQcagN1TiJ/Hpxngc/ZSId5Lc5Lw9EypoFKEXmEMA926f9SoNdAZD9dDW34CT9YlNPUGJQhcZR4ykmn5emQbKhsrtCKa4xPGoXmaNFNHWwEuwup193+OZ4m78Klmck6x+uZcO8fANO3o2Tep60qpP+jkRNrmidgeSSbdVp8+DDTleALWHBKCq991ur9gvSMVyzU6ljOAPS+P5EpNIDer9US8jjk2u9o0VUNO5QUMweFH3dLCjMsVy/NgpNrMGnN70ou/pONMJPE2xokbDy+xhFmoj3fwgK/a+7db+0r+/hXpEpbZNMzTxqztkdy+On397z4JtPHBvkre58MDrFMm8IDoCzyKmoqmTOuiqK+zyNpUSVBDD0w0aVuN0bf3UKdZveUlY3OPrrWRyeoDdefw29C1kQEyeRRgFTNArn8gCOoZzaIgAdDItTw3Ds+vMOL7g==
  template:
    metadata:
      creationTimestamp: null
      name: bucket-s3
      namespace: minio
    type: Opaque
