apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bucket-s3
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgAUbcW1K/mEaynRZebOcGJu1Y4+DPo+ljtsN+mKChqi6u+X1DaJk0wCkOeVab3/ynY5Ttye5qfEhsI4rkYGOTXDvpRPHqdlIoSnxhwVWnQfPKVxuZj11LD1xuHNM17AXEzfFJpQNmyKG+rtGWCj/u1hQIwbACSb/IFBh7us+yAOO3JShhEo26hDwMkMNtTTDRzwSWxihzv+cDJ0/iFYCNHjvbS/Q6LsQpBlHwt/jKj4ZOOorMwjLsmR/SInXVNeQRVuWIuGme/lrqVMa5pH6TY9rmie8Yykf0KKInqkIMR41HQVWcn7NRq9mLzbfU6qaAHNs3v4jBRMYRENUpzGy9gHh7Vr0CsWHnnkCx4U7BTyC47T1awrBWM8PeglXalx16uF/db8mUsZtHfE/4Uw7U8aPP39X3ZbnWF8fXyGFfGW01DkX1/GjR4uXrTiyd/17lBT2FCBUqLbppUNdP2D6KZlYRufUroRYSdUzi+2FsyK5kTFa7KbSLAXY+TTS8pu/u8IGwYaj3smFQH3sNHiWFnp+yi4MlojBxdRhivmNF5BZjSO0lX3A6yZ6IfXf/iKwPT4HPC7z17hx2M20PqFcrM7onm/9icI1mRswp1qOctVL4LIld1Y02dVJp+TqaKfV+w1KwYUBDMExdjWQYIUJOcnu/mNl8tm6HodY0dxhzWUyi/d2O+vdQTSvQhCLi9OG4FkZvq6RrRSYESMOjtKGgQxF34Lf0Uzo90barfmuU05azeQ8pL4j8Oe
    rootUser: AgDMWVflR7T+KKD9K493DlGtsiaqXNWl9SUq8oxWNMQMEpm+zJfgeWCXQ2jbyrQl9+Bf7LxoFAL5+g+GMwb7geN8jwRCM7O4vIy7Z/LpNR8RwxTuL0kg7oAFqm6aSWzXLQE9oKjavbRF/SikQhnBZviqQvVqDbZTVpmgM4K58WOE3s8Kk+3G/uWQKX3t8GeNFqfIE3VwbaqsW10BOyNHpB7mtSURptBPD+aXekq5+m/dWCi4pbxtyJY/mOSkNoixxETls4qhZ0GEap1bBGMbG84z2lcj5cA5e1D05um50J97AFVEXvyz1jz+ecLdBSCe09XnajKzjkjLCoheKWo3Qj6m7PxCMHGG71qFRzkgxgzc5Hnl5YhHh/VDzF4GfzgyCPN5QZpUyUmUt/h7cXDrxdzeldZ5yebM+wKDYEI4HmG5Q70xLDVDGUuuzzEGl59gdx9HvjmxI1hYrXDWkoVpj9BUPp2Pc+s0CVBgXEWQw5HCtF+ymouWaz5KnvzovJ2+VTvfst+oPFidtI3isojX9+8oDr1tOmWwgOQGB765jI1RJt27+2eRyA4gmiSQgL3xN9S58L7sGYRKu3jf+WY6YchlV5ojJWuTGQ3lMLVjIDTzh1czHBG8GnPIn5scDjKaFENuOWzfp0VSmjso12O7uMN87rQb8fnHeq6BlNMiLHZQLD+SgO2fVCXQAdKQVDifQYOC9Qn+DQ==
  template:
    metadata:
      creationTimestamp: null
      name: bucket-s3
      namespace: minio
    type: Opaque
