apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bucket-s3
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgBarGxQrkwCQ7CgJj0Ov6tJVgImJxjTmMkT99mVdwjRVLcJXx8hNXUeKfwXh+v7ojCXVQltq6NZn+hWBixxgdg/4X/dWnPpv0Eq0IE8RpcgnYFkxC05HV+kjycvRtaugLoG3tE6ZMf1nIePbeRH/ndL79oZslIBTX6jLAF66Kq1XDD4GcnRN6Fkw7dzGFCgr0GqYzdwhHqgCaxJs+zJw5Yz1aPN9Mu+A0rCKsBccpyt5M/VOV1FP36Iw+e5Wb+LngtpLQyO3i8c0BuHdmIgvyfwb3w30tatMTmBV2Yl4lQnHfaoZwO/4lInufia2PUV77BZPeYjzWPsGrrH0lLtysToTlPE46axiMhlb+dn++PEQHNqzbPOSj6pLSUt1/afLSl9P64mSF4KIdNE7CkkwBZ06AmOV15XYbrwKZUF9DCtJBe73og1qqxR+bHd4EzrRi/OOWH5wI1+0P2DH1QafuEKVHUuCTstBZ1wkcB2AHj2YS+Qip7HkgJnp2inEyoRKcKYArvXFP2zOtxKi7Cud/n8R0TKAGNtzoSyU8unU9AsoOVZaVZ5aOITa6Z/g02WT+Y3zGjKFur5kCqwP55rrjptZSjES72teYAz/n7awyDklRV+nUF7z0F2znYS44zLAd3FuSpjXxjPZNesWKgbp5eUnnglBFjp7R5mQ/n1wrHfXatLed7TfhxMkyE2YDMaMqfPenWRGc7hPpYeXP353eIAhGto8OSPQ52WgZS+EvKLJ3NNRQ06vmtQ
    rootUser: AgCQRMbj9nND7/Vsbk//FqDWcHkHbMovErNwahIZb5l+1YA9ynGxnsFtTr1fa9EiC2uAEIZX8fYU1jdeVNDVXfrquv/XFD9jh8bunHwSjQrJIzRCEoF4G/VAGl3d+PPgQUHnocY1ppRK0b/UNKvhV6LrT2M9DHb5MlBGg4+ogbihY4Ca0auCDBGMh5u0MTyIGlicJ/UY5Y+KblafsYpi4qBQsJiIBexHfikrYzpFupHmjRosg8242DfBrg/IUhlrRb+KYvakW6KDBbejOsdM61ItSaSXS02mdc4aQmi6BuBXG1YtkUltdAAgIa7T7XTOtZ5ntJ8LW4ZMWzE0JXWWTttu7H9SgRUovqJ03aL7UBgmEuGUbZDRSuO1AFGLhZ89oYcgWTawGjDL1HipFnAFleI5v+tXoAp25AqD0F71kaLVN3/imI+78yQxGKKSkaCOQV9Yh6RWObtTX9tbMpk4qt002MTmVubTpd4a3hhz8lBSSDmTVS/aCS/vZLNygGj9ioTwsv0rXhjSll9iaNFLGgh1+N4tLjo1bKsfosOBlAlLGC6Qbrqi7tJa2QrblXI8TUy+4Ujli5hB+yzcx1xZ9FaOqxidPZ+i2fMWST9VuR3V7mkINc9bCYEmTrYY/rmMtmm27tb/sSQIzQCaSkkLBlheZ2g/HpNQwBHpGTUCqwzrHoDi50X3Iqiy6stDI1bgp8UPHcdmBg==
  template:
    metadata:
      creationTimestamp: null
      name: bucket-s3
      namespace: minio
    type: Opaque
