# kube-prometheus-stack
# artifacthub                                                   https://artifacthub.io/packages/helm/prometheus-community/kube-prometheus-stack
# values.yaml                                                   https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml
# kube-prometheus-stack-and-argocd-how-workarounds-are-born     https://blog.ediri.io/kube-prometheus-stack-and-argocd-how-workarounds-are-born
#
# grafana
# helm chart                                                    https://grafana.github.io/helm-charts
# values.yaml                                                   https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
# how-to-securely-reference-secrets-in-grafanaini               https://github.com/grafana/helm-charts/tree/main/charts/grafana#how-to-securely-reference-secrets-in-grafanaini
#
# prometheus-node-exporter
# helm chart                                                    https://prometheus-community.github.io/helm-charts
# values.yaml                                                   https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-node-exporter/values.yaml
#
# kube-state-metrics
# helm chart                                                    https://prometheus-community.github.io/helm-charts
# values.yaml                                                   https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/values.yaml
#
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kube-prometheus-stack-helm-chart
name: &name kube-prometheus-stack
version: 64.0.0                                                 # https://github.com/prometheus-community/helm-charts/compare/kube-prometheus-stack-38.0.0...kube-prometheus-stack-43.0.0
repo: https://prometheus-community.github.io/helm-charts
releaseName: *name
namespace: monitoring
includeCRDs: false
valuesFile: values.yaml
valuesMerge: merge                 # merge, override or replace
valuesInline:
  fullnameOverride: kube-prometheus-stack
  grafana:
    additionalDataSources:
    - name: Loki
      access: proxy
      type: loki
      url: http://loki-distributed-gateway.loki.svc.cluster.local
      version: 1
    persistence:
      enabled: true
    plugins:
    - grafana-piechart-panel
    - grafana-worldmap-panel

    ## Deploy default dashboards
    ##
    defaultDashboardsEnabled: false

    ## Timezone for the default dashboards
    ## Other options are: browser or a specific timezone, i.e. Europe/Luxembourg
    ##
    defaultDashboardsTimezone: Europe/Paris

    sidecar:
      dashboards:
        # Log level. Can be one of: DEBUG, INFO, WARN, ERROR, CRITICAL.
        logLevel: DEBUG
        # provider configuration that lets grafana manage the dashboards
        provider:
          # allow updating provisioned dashboards from the UI
          allowUiUpdates: true

  prometheus: {}
    # prometheusOperator:
    #   resources:
    #     limits:
    #       cpu: 200m
    #       memory: 200Mi
    #     requests:
    #       cpu: 100m
    #       memory: 100Mi

  kube-state-metrics:
    resources:
      limits:
        cpu: 100m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi

  prometheus-node-exporter:
    prometheus:
      monitor:
        enabled: true
        # additionalLabels:
        #   release: kube-prometheus-stack
    resources:
      limits:
        cpu: 200m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 30Mi

