# artifacthub                                       https://artifacthub.io/packages/helm/minio-official/minio
#                                                   https://github.com/minio/minio/tree/master/helm/minio
# releases                                          https://github.com/minio/minio/tree/master/helm-releases
# values.yaml                                       https://github.com/minio/minio/blob/master/helm/minio/values.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: minio-helm-chart
name: &name minio
version: 4.1.0 # 4.0.2 => 5.0.1                     https://github.com/minio/minio/compare/RELEASE.2022-05-08T23-50-31Z...RELEASE.2022-11-11T03-44-20Z
# https://github.com/minio/minio/compare/RELEASE.2022-05-08T23-50-31Z...RELEASE.2022-10-29T06-21-33Z
repo: https://charts.min.io
releaseName: *name
namespace: *name
includeCRDs: false
valuesFile: values.yaml
valuesMerge: merge                 # merge, override or replace
valuesInline:
  image:
    pullPolicy: Always
  
  mode: standalone # standalone or distributed
  # replicas: 4

  DeploymentUpdate:
    type: Recreate #RollingUpdate
    maxUnavailable: ~ #0
    maxSurge: ~ #100%

  persistence:
    accessMode: ReadWriteOnce
    enabled: true
    size: 512Mi #10Gi

  resources:
    limits:
      cpu: 100m #250m #500m #1
      memory: 256Mi #384Mi #512Mi #1Gi #4Gi
    requests:
      cpu: 20m #100m #250m #500m
      memory: 100Mi #128Mi #256Mi #2Gi

  configPathmc: "/tmp/minio/mc/"
  # certsPath: "/tmp/minio/certs/"

  makePolicyJob:
    securityContext:
      enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
  
  makeUserJob:
    securityContext:
      enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
  
  makeBucketJob:
    securityContext:
      enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi

  customCommandJob:
    securityContext:
      enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
