existingSecret: bucket-s3
ingress:
  enabled: false
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
    kubernetes.io/tls-acme: "true"
    # acme.cert-manager.io/http01-ingress-class: ingress-nginx-admin
  ingressClassName: ingress-nginx-admin
  hosts:
  - minio-api.admin.plato-devncoargo.dev-sbr.com
  tls:
  - secretName: minio-api-tls-certificate
    hosts:
    - minio-api.admin.plato-devncoargo.dev-sbr.com
consoleIngress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    # acme.cert-manager.io/http01-ingress-class: ingress-nginx-admin
  ingressClassName: ingress-nginx-admin
  hosts:
  - minio-console.admin.plato-devncoargo.dev-sbr.com
  tls:
  - secretName: minio-console-tls-certificate
    hosts:
    - minio-console.admin.plato-devncoargo.dev-sbr.com
buckets:
    # Name of the bucket
  - name: loki
    # Policy to be set on the
    # bucket [none|download|upload|public]
    policy: public
    # Purge if bucket exists already
    purge: false
    # set versioning for
    versioning: ~ # true, false or ~ (standalone) 
    # Name of the bucket
  - name: logs
    # Policy to be set on the
    # bucket [none|download|upload|public]
    policy: public
    # Purge if bucket exists already
    purge: false
    # set versioning for
    versioning: ~ # true, false or ~ (standalone)
## OpenID Identity Management
## The following section documents environment variables for enabling external identity management using an OpenID Connect (OIDC)-compatible provider.
## See https://min.io/docs/minio/linux/operations/external-iam/configure-openid-external-identity-management.html for a tutorial on using these variables.
oidc:
  enabled: false
  configUrl: https://keycloak-01.admin.plato-devncoargo.dev-sbr.com/realms/master/.well-known/openid-configuration
  clientId: minio
  clientSecret: vgnExUewhNvj0WbrNOppntJ4qc1NQyjl
  claimName: policy
  scopes: openid,profile,email
  redirectUri: https://minio-console.admin.plato-devncoargo.dev-sbr.com/oauth_callback
  # Can leave empty
  claimPrefix: ""
  comment: ""
persistence:
  accessMode: ReadWriteOnce
  enabled: true
  size: 3Gi #2048Mi #10Gi
  storageClass: gp2-with-volume-expansion