apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
spec:
  generators:
  - git:
      repoURL: https://github.com/kube-components-stack/kustomization.git
      revision: HEAD
      files:
      - path: "apps/ingress-nginx/**.yaml"
  template:
    metadata:
      name: '{{name}}-ingress-nginx'
    spec:
      project: "default"
      source:
        helm:
          valueFiles:
          - values.yaml
          values: |-
            {{values}}
        repoURL: https://github.com/kubernetes/ingress-nginx.git
        targetRevision: helm-chart-4.1.3
        path: "charts/ingress-nginx"
      destination:
        server: '{{address}}'
        namespace: ingress-nginx
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 2m
          limit: 5
        syncOptions:
          - Validate=false
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - RespectIgnoreDifferences=true
