apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bucket-s3
  namespace: loki
spec:
  encryptedData:
    awsAcessKeyId: AgA+X4w1UIaH18O32iyiBlbPHpykvJe8kIh9tAluLd1Wfgj22j/HDC+XhlzWUWdsUaAMstOIG3M/RT1HQpCmo7jLq2/oayjocN52dfJUV38FhYYXJZqTemYx4Ocp/u+kULCDjOZyv9UHvWHsWXyEGQkTl/raVEvof/6+sbgSD5PFusfn4MD0KYoo8s/kTjQmMiutEwxSoq8rQJKzUrDPOcO5YOf7R0qQ31uiSVjX0uAwgPllPuaWKrqk6QCX73JszFrv9vclQtlTvwGoIb+Gry27YoGrXvoKGFpGDsMssTjSk1EMGCI8z9+4c9N11qOhsysy/ipXfF7PHoonexddlq6VBNZ829M/JMVUS8r0J7AIH+Cr0/R9BkWYDrRB2Ge11WoCXf/7xL3pIxDt6143WCaLcFFiZoQy+7rLqwmDNQRBoTZhEQ1/pYix74UM0pPSpC2p6djIdSbZrMRInMoEqFji1tp1e2X1aLlwParszAMEHGqWQCfSmktlK72NrKxtJIJ1Rz2SEl6RH2gE+w5VaRoKF7ZRIuQdTGTznEhNRVtBbViHmZiMPT+oYl77jwoD4NXkidLd/2bUQ/PXFQ9UnJtMowKfF+mbhBcp9bZiAajYyt62N9U+3nCUZFWf2w5l2hkJGx2duq8kmOciF62J9PVSLt/iErXhu/m1h0G2lrbPH+xBAalxhsb/1ouuSmi/H6/9/G6VUA==
    awsSecretAcessKey: AgAb7UeksoljjgDwxalgc2/rcOO/oE1X255vKlULcHUxLfvVlr+gxfzZT8ALU0NvLF6yNF1vS0iOAASWJchR1+2vLJMSatZXtKsmyhkDKJimjXDJtKtvv+kfn4XoIg7yp2+2UOu0ybC8h9EyzHhQ2Wb6uL2ANHX0NF4WrcRJ2qc4B0DTkjvce6EyhcniOBOg5cY17+4/mJasgFua7DA8D7bikqd5j6ADAJbKu42DpHAa5D82LcZSvnIe931KdnU4cYtTOZNtKCBPBm++jZ7oPB0w+2L0bSwOJgp2R/mSGYXzoBKcMQSM3kqUdP+DDbTKD8vWplZ+xQ1irCYAYqmldrktNqBpFQamnixnBYiCc4XxfEw46V9F4ZSs7bfQLbnGXvkhRs+hg/LyP0Rowul+7WCSyRuSP91vYObQ/UPt6lR7yr9Rk3s80Rvs3oBa1vsXwuwV8KRSSZDM3gQCaM8yyWvhq6gPDgCi1Yxq9yOT4GhXHRmuDpfpoJR/mzrHKwmcUjjW2UbaXfQygI1nEfnKCo0wG0ahkxEnRrouZLZvW1QS3RDh4MrYv5d/DJthHE8Jd0Gst1uZ5NaibSNNVNMxzl6ZiNHyT0DFc74IFVexzJCopufZzbowbhIZ0pG73ufzZVtACyV5mTQZ7rb+Gm5kEiWvav0fA88m48QWy8v+GzMisc1O50QvcrXTioBYwrqVcIB7j7i9JJzpTw==
  template:
    metadata:
      creationTimestamp: null
      name: bucket-s3
      namespace: loki
    type: Opaque
