apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: keycloak
generators:
- ../../base/helm-generator.yaml
resources:
- ../../base
- secrets.yaml
transformers:
- transformer-annotation-job-keycloak-config-cli.yaml