---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: keycloak
spec:
  containers:
  - 
    # command:
    # - java
    # - -jar
    # - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-18.0.0.jar
    command:
      - sh
      - "-c"
      - |
        /bin/bash <<'EOF'
        tail -f /dev/null
        EOF
      # java -jar /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.3.jar
    env:
    # - name: KEYCLOAK_URL
    #   value: http://keycloak-headless.keycloak.svc.cluster.local:8080/
    - name: KEYCLOAK_URL
      value: http://keycloak-headless:8080/
    - name: KEYCLOAK_USER
      value: user
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          key: admin-password
          name: keycloak-auth
    - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
      value: "true"
    - name: IMPORT_FILES_LOCATIONS
      value: /secret/*
    # docker run quay.io/skopeo/stable:latest list-tags docker://docker.io/bitnami/keycloak-config-cli  | yq e -P
    image: docker.io/bitnami/keycloak-config-cli:5.5.0-debian-11-r8
    imagePullPolicy: IfNotPresent
    name: keycloak-config-cli
    resources:
      limits: {}
      requests: {}
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
    volumeMounts:
      - mountPath: /secret
        name: cfg
        readOnly: true
  restartPolicy: Never
  securityContext:
    fsGroup: 1001
  serviceAccountName: keycloak
  volumes:
    - name: cfg
      secret:
        secretName: keycloak-config