---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak-keycloak-config-cli
  namespace: keycloak
spec:
  containers:
  - 
    # command:
    # - java
    # - -jar
    # - /opt/bitnami/keycloak-config-cli/keycloak-config-cli-18.0.1.jar
    command:
      - sh
      - "-c"
      - |
        /bin/bash <<'EOF'
        tail -f /dev/null
        EOF
    
    env:
    # - name: KEYCLOAK_URL
    #   value: http://keycloak-headless.keycloak.svc.cluster.local:8080/
    - name: KEYCLOAK_URL
      value: http://keycloak-headless:8080/
    - name: KEYCLOAK_USER
      value: user
    - name: KEYCLOAK_PASSWORD
      valueFrom:
        secretKeyRef:
          key: admin-password
          name: keycloak-auth
    - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
      value: "true"
    - name: IMPORT_FILES_LOCATIONS
      value: /secret/*
    image: docker.io/bitnami/keycloak-config-cli:5.2.0-debian-11-r5
    imagePullPolicy: IfNotPresent
    name: keycloak-config-cli
    resources:
      limits: {}
      requests: {}
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
  restartPolicy: Never
  securityContext:
    fsGroup: 1001
  volumeMounts:
    - mountPath: /secret
      name: cfg
      readOnly: true
  serviceAccountName: keycloak
  volumes:
    - name: cfg
      secret:
        secretName: keycloak-config