---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: keycloak
  labels:
    foo: bar
spec:
  terminationGracePeriodSeconds: 5
  containers:
  - 
    name: keycloak-config-cli
    command:
      - sh
      - "-c"
      - |
        /bin/bash <<'EOF'
          apt update && apt install -y dnsutils curl ncat openssl

          env | sort

          set -x
          dig A +short keycloak-headless.keycloak.svc.cluster.local
          nc -w 5 -vz keycloak-headless.keycloak.svc.cluster.local 8080
          nc -w 5 -vz keycloak-headless.keycloak.svc.cluster.local 8443

          dig A +short keycloak.keycloak.svc.cluster.local
          nc -w 5 -vz keycloak.keycloak.svc.cluster.local 80
          nc -w 5 -vz keycloak.keycloak.svc.cluster.local 443

          output=$(curl \
            --write-out "%{http_code}" \
            --data "client_id=admin-cli" \
            --data "username=${KEYCLOAK_USER}" \
            --data "password=${KEYCLOAK_PASSWORD}" \
            --data "grant_type=password" \
            "${KEYCLOAK_URL}realms/master/protocol/openid-connect/token")
          
          echo "$output"

          KEYCLOAK_URL=https://keycloak-headless.keycloak.svc.cluster.local:8443/
          output=$(curl \
            --write-out "%{http_code}" \
            --data "client_id=admin-cli" \
            --data "username=${KEYCLOAK_USER}" \
            --data "password=${KEYCLOAK_PASSWORD}" \
            --data "grant_type=password" \
            --insecure \
            "${KEYCLOAK_URL}realms/master/protocol/openid-connect/token")
          
          echo "$output"

          echo "" | openssl s_client -showcerts -connect keycloak-headless.keycloak.svc.cluster.local:8443 2>&1 |\
          sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p;/-END CERTIFICATE-/a\\x0' |\
          sed -e '$ d' |\
          xargs -0rl -I% sh -c "echo '%' | openssl x509 -subject -issuer -dates -fingerprint -noout"

          tail -f /dev/null
        EOF
      # java -jar /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.3.jar
    env:
      - name: KEYCLOAK_URL
        value: http://keycloak-headless.keycloak.svc.cluster.local:8080/
      - name: KEYCLOAK_USER
        value: user
      - name: KEYCLOAK_PASSWORD
        valueFrom:
          secretKeyRef:
            key: admin-password
            name: keycloak-auth
      - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
        value: "true"
      - name: IMPORT_FILES
        value: /secret/*
      - name: LOGGING_LEVEL_ROOT
        value: debug
    # docker run quay.io/skopeo/stable:latest list-tags docker://docker.io/bitnami/keycloak-config-cli  | yq e -P
    image: docker.io/bitnami/keycloak-config-cli:5.5.0-debian-11-r4
    # image: docker.io/bitnami/keycloak-config-cli:5.5.0-debian-11-r8
    imagePullPolicy: IfNotPresent
    resources:
      limits: {}
      requests: {}
    securityContext:
      allowPrivilegeEscalation: true
      runAsNonRoot: false
      runAsUser: 0
    volumeMounts:
      - mountPath: /secret
        name: cfg
        readOnly: true
  restartPolicy: Never
  securityContext:
    fsGroup: 0
  serviceAccountName: keycloak
  volumes:
    - name: cfg
      secret:
        secretName: keycloak-config