## @param proxy reverse Proxy mode edge, reencrypt, passthrough or none
## ref: https://www.keycloak.org/server/reverseproxy
##
proxy: edge # passthrough/edge/none/reencrytpt

auth:
  adminUser: &adminUser foo
  adminPassword: &adminPassword bar 
ingress:
  enabled: true
  ingressClassName: ingress-nginx-admin
  hostname: &hostname keycloak.admin.plato-devncoargo.dev-sbr.com
  annotations:
    kubernetes.io/tls-acme: "true"
  extraTls:
  - secretName: *hostname
    hosts:
      - *hostname
# https://github.com/adorsys/keycloak-config-cli
# https://github.com/adorsys/keycloak-config-cli/blob/main/docs/FEATURES.md
keycloakConfigCli:
  enabled: true
  extraEnvVars:
  - name: KEYCLOAK_URL
    value: http://keycloak-headless:8080/
  - name: KEYCLOAK_USER
    value: *adminUser
  - name: KEYCLOAK_PASSWORD
    value: *adminPassword
  - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
    value: "true"
  - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
    value: 60s
  - name: IMPORT_FILES
    value: /secret/*
  - name: LOGGING_LEVEL_ROOT
    value: debug
  extraVolumeMounts:
  - mountPath: /secret
    name: cfg
    readOnly: true
  extraVolumes:
  - name: cfg
    secret:
      secretName: keycloak-config
  command:
    - sh
    - "-c"
    - |
      /bin/bash <<'EOF'
      tail -f /dev/null
      EOF
    # - |
    #   /bin/bash <<'EOF'
    #   java -jar /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.3.jar --keycloak.url=http://keycloak-headless.keycloak.svc.cluster.local:8080/ --keycloak.ssl-verify=false --keycloak.user=foo --keycloak.password=bar --import.files.locations=/secret/config.yaml --logging.level.root=debug
    #   EOF

postgresql:
  architecture: standalone
  auth:
    database: bitnami_keycloak
    existingSecret: ''
    password: bar
    username: bn_keycloak
  enabled: true