## @param proxy reverse Proxy mode edge, reencrypt, passthrough or none
## ref: https://www.keycloak.org/server/reverseproxy
##
# proxy: edge # passthrough/edge/none/reencrytpt

auth:
  adminUser: &adminUser admin
  adminPassword: &adminPassword admin
  managementUser: manager
  managementPassword: manager

postgresql:
  auth:
    password: password

service:
  type: ClusterIP
#   http:
#     enabled: false

# tls:
#   enabled: false

ingress:
  enabled: true
  ingressClassName: ingress-nginx-admin
  hostname: &hostname keycloak.admin.plato-devncoargo.dev-sbr.com
  annotations:
    kubernetes.io/tls-acme: "true"
  extraTls:
  - secretName: *hostname
    hosts:
      - *hostname
# https://github.com/adorsys/keycloak-config-cli
# https://github.com/adorsys/keycloak-config-cli/blob/main/docs/FEATURES.md
keycloakConfigCli:
  enabled: false
  extraEnvVars:
  - name: KEYCLOAK_URL
    value: http://keycloak-headless.keycloak.svc.cluster.local:8080
  - name: KEYCLOAK_USER
    value: *adminUser
  - name: KEYCLOAK_PASSWORD
    value: *adminPassword
  # - name: KEYCLOAK_GRANTTYPE
  #   value: password
  # - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
  #   value: "true"
  # - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
  #   value: 60s
  - name: IMPORT_FILES
    value: /secret/*
  # - name: LOGGING_LEVEL_ROOT
  #   value: debug
  extraVolumeMounts:
  - mountPath: /secret
    name: cfg
    readOnly: true
  extraVolumes:
  - name: cfg
    secret:
      secretName: keycloak-config
  command:
    - sh
    - "-c"
    - |
      /bin/bash <<'EOF'
      java -jar /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.3.jar --import.files.locations=/secret/config.yaml --keycloak.ssl-verify=false
      EOF
    # tail -f /dev/null
    # - |
    #   /bin/bash <<'EOF'
    #   apt update && apt install -y dnsutils curl ncat openssl
    #   dig A +short keycloak-headless.keycloak.svc.cluster.local
    #   nc -vz keycloak-headless.keycloak.svc.cluster.local 8080
    #   echo "" | openssl s_client -showcerts -connect 127.0.0.1:8080 2>&1

    # https://www.keycloak.org/docs/latest/server_development/#authenticate-with-a-service-account
    # curl \
    #   --write-out "%{http_code}" \
    #   -d "client_id=admin-cli" \
    #   -d "username=foo" \
    #   -d "password=bar" \
    #   -d "grant_type=password" \
    #   "http://keycloak-headless.keycloak.svc.cluster.local:8080/realms/master/protocol/openid-connect/token"
    # {"error":"invalid_request","error_description":"HTTPS required"}403
    # 

    #   java -jar /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.3.jar --keycloak.url=http://keycloak-headless.keycloak.svc.cluster.local:8080/ --keycloak.ssl-verify=false --keycloak.user=foo --keycloak.password=bar --import.files.locations=/secret/config.yaml --logging.level.root=debug
    #   java -jar /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.3.jar --keycloak.url=http://keycloak-headless.keycloak.svc.cluster.local:8080/auth --keycloak.ssl-verify=false --keycloak.user=foo --keycloak.password=bar --import.files.locations=/secret/config.yaml --logging.level.root=debug
    #   EOF

