auth:
  adminUser: foo
  adminPassword: bar 
ingress:
  enabled: true
  ingressClassName: ingress-nginx-admin
  hostname: &hostname keycloak.admin.plato-devncoargo.dev-sbr.com
  annotations:
    kubernetes.io/tls-acme: "true"
  extraTls:
  - secretName: *hostname
    hosts:
      - *hostname
# https://github.com/adorsys/keycloak-config-cli
# https://github.com/adorsys/keycloak-config-cli/blob/main/docs/FEATURES.md
# keycloakConfigCli:
#   enabled: true

postgresql:
  architecture: standalone
  auth:
    database: bitnami_keycloak
    existingSecret: ''
    password: bar
    username: bn_keycloak
  enabled: true