# kustomize build --enable-alpha-plugins --enable-helm --load-restrictor LoadRestrictionsNone addons/apps/keycloak/overlays/plato-devncoargo|yq -ojson|jq -s|jq '.[]|select(.kind == "ConfigMap")'|jq -s|yq e -P
# JAVA_OPTS_APPEND: -Djgroups.dns.query=keycloak-headless.keycloak.svc.cluster.local
# KEYCLOAK_ADMIN: user
# KEYCLOAK_CACHE_STACK: kubernetes
# KEYCLOAK_CACHE_TYPE: ispn
# KEYCLOAK_DATABASE_HOST: keycloak-postgresql
# KEYCLOAK_DATABASE_NAME: bitnami_keycloak
# KEYCLOAK_DATABASE_PORT: "5432"
# KEYCLOAK_DATABASE_USER: bn_keycloak
# KEYCLOAK_ENABLE_HTTPS: "true"
# KEYCLOAK_ENABLE_STATISTICS: "false"
# KEYCLOAK_HTTP_PORT: "8080"
# KEYCLOAK_HTTPS_CERTIFICATE_FILE: /opt/bitnami/keycloak/certs/tls.crt
# KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE: /opt/bitnami/keycloak/certs/tls.key
# KEYCLOAK_HTTPS_PORT: "8443"
# KEYCLOAK_HTTPS_USE_PEM: "true"
# KEYCLOAK_LOG_OUTPUT: default
# KEYCLOAK_PRODUCTION: "false"
# KEYCLOAK_PROXY: edge


production: true

# keycloak 18
extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG

  # - name: KC_SPI_TRUSTSTORE_FILE_FILE
  #   value: /truststore/truststore.jks
  # - name: KC_SPI_TRUSTSTORE_FILE_PASSWORD
  #   value: changeit
  #   ## Activate nginx provider
  # - name: KC_SPI_X509CERT_LOOKUP_PROVIDER
  #   value: nginx
  #   ## Set nginx provider header name
  # - name: KC_SPI_X509CERT_LOOKUP_NGINX_SSL_CLIENT_CERT
  #   value: ssl-client-cert
  #   ## Set loglevel for the nginx provider
  # - name: QUARKUS_LOG_CATEGORY__ORG_KEYCLOAK_SERVICES_X509__LEVEL
  #   value: TRACE

  # - name: KC_HOSTNAME_STRICT_HTTPS
  #   value: "false"
  # - name: KC_HOSTNAME_STRICT
  #   value: "false"
  # - name: KC_HOSTNAME_STRICT_BACKCHANNEL
  #   value: "true"
  # - name: KC_HOSTNAME
  #   value: keycloak.keycloak.svc.cluster.local
  # - name: KC_HOSTNAME_URL
  #   value: https://keycloak-01.admin.plato-devncoargo.dev-sbr.com

auth:
  existingSecret: keycloak-auth
  passwordSecretKey: admin-password

ingress:
  enabled: true
  ingressClassName: ingress-nginx-admin
  hostname: &hostname keycloak-01.admin.plato-devncoargo.dev-sbr.com
  annotations:
    kubernetes.io/tls-acme: "true" # one of certmanager annotations: cert-manager.io/cluster-issuer, cert-manager.io/issuer or kubernetes.io/tls-acme
  tls: true
  # selfSigned: false

tls: 
  enabled: true
  autoGenerated: true
  existingSecret: keycloak-ca

## @param proxy reverse Proxy mode edge, reencrypt, passthrough or none
## ref: https://www.keycloak.org/server/reverseproxy
##
proxy: edge #reencrypt #edge #reencrypt

service:
  type: ClusterIP
  http:
    enabled: true

# https://github.com/adorsys/keycloak-config-cli
# https://github.com/adorsys/keycloak-config-cli/blob/main/docs/FEATURES.md
# https://hub.docker.com/r/adorsys/keycloak-config-cli
keycloakConfigCli:
  enabled: true
  extraEnvVars:
  - name: KEYCLOAK_URL
    value: https://keycloak-headless:8443/
  - name: LOGGING_LEVEL_ROOT
    value: debug
  extraVolumeMounts:
  - mountPath: /import
    name: cfg
    readOnly: true
  extraVolumes:
  - name: cfg
    secret:
      secretName: keycloak-config
  command:
   - sh
   - "-c"
   - |
     /bin/bash <<'EOF'
      java -jar /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.3.jar --import.files.locations=/import/config.yaml --keycloak.ssl-verify=false
     EOF