extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG

## @param proxy reverse Proxy mode edge, reencrypt, passthrough or none
## ref: https://www.keycloak.org/server/reverseproxy
##
# proxy: edge # passthrough/edge/none/reencrytpt

auth:
  existingSecret: keycloak-auth
  passwordSecretKey: admin-password
ingress:
  enabled: true
  ingressClassName: ingress-nginx-admin
  hostname: &hostname keycloak.admin.plato-devncoargo.dev-sbr.com
  extraTls:
  - secretName: keycloak-ca #keycloak-tls-certificate
    hosts:
      - *hostname
  annotations:
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.org/server-snippets: |
      location /auth {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
      }
tls: 
  enabled: true
  # existingSecret: keycloak-ca
  autoGenerated: true
service:
  type: ClusterIP
  http:
    enabled: true

# https://github.com/adorsys/keycloak-config-cli
# https://github.com/adorsys/keycloak-config-cli/blob/main/docs/FEATURES.md
# https://hub.docker.com/r/adorsys/keycloak-config-cli
keycloakConfigCli:
  enabled: true
  extraEnvVars:
  - name: KEYCLOAK_URL
    value: https://keycloak-headless:8443/
  - name: LOGGING_LEVEL_ROOT
    value: debug
  extraVolumeMounts:
  - mountPath: /import
    name: cfg
    readOnly: true
  extraVolumes:
  - name: cfg
    secret:
      secretName: keycloak-config
  command:
   - sh
   - "-c"
   - |
     /bin/bash <<'EOF'
      java -jar /opt/bitnami/keycloak-config-cli/keycloak-config-cli-19.0.3.jar --import.files.locations=/import/config.yaml --keycloak.ssl-verify=false
     EOF