# artifacthub                                       https://artifacthub.io/packages/helm/vector/vector
# github                                            https://github.com/vectordotdev/helm-charts/tree/master/charts/vector
# values.yaml                                       https://github.com/vectordotdev/helm-charts/blob/master/charts/vector/values.yaml
# configmap.yaml                                    https://github.com/vectordotdev/helm-charts/blob/master/charts/vector/templates/configmap.yaml
# Logstash, Fluentd, Fluent Bit, or Vector?         https://www.cncf.io/blog/2022/02/10/logstash-fluentd-fluent-bit-or-vector-how-to-choose-the-right-open-source-log-collector/
# Store observability events in GCP Cloud Storage   https://vector.dev/docs/reference/configuration/sinks/gcp_cloud_storage/
# ingress-nginx Log format                          https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/log-format/#log-format
# regex101                                          https://regex101.com/r/n8YqXK/1
# regex                                             /^(?P<remote_addr>\S+) - (?P<remote_user>\S+) \[(?P<time_local>[^\]]+)\] "(?P<request>[^"]+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]+)" \"(?P<http_user_agent>[^"]+)" (?P<request_length>\d+) (?P<request_time>\d+\.\d+) \[(?P<proxy_upstream_name>[^\]]*)\] \[(?P<proxy_alternative_upstream_name>[^\]]*)\] (?P<upstream_addr>[0-9\.a-z\/]+:[0-9\.a-z\/]+(?:, [0-9\.a-z\/]+:[0-9\.a-z\/]+)*) (?P<upstream_response_length>\d+(?:, \d+)*) (?P<upstream_response_time>\d+\.\d+(?:, \d+\.\d+)*) (?P<upstream_status>(?:\d+|-)(?:, (?:\d+|-))*) (?P<req_id>\S+)$/gm
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: vector-helm-chart
name: &name vector
version: 0.13.1
repo: https://helm.vector.dev
releaseName: *name
namespace: vector
includeCRDs: false
valuesFile: values.yaml
valuesMerge: override                 # merge, override or replace
valuesInline:
  service:
    enabled: false
  data_dir: /vector-data-dir

  # role -- Role for this Vector (possible values: Agent, Aggregator, Stateless-Aggregator)
  ## Ref: https://vector.dev/docs/setup/deployment/roles/
  ## Each role is created with the following workloads:
  ## Agent - DaemonSet
  ## Aggregator - StatefulSet
  ## Stateless-Aggregator - Deployment
  role: Agent
  
  # https://vector.dev/docs/setup/installation/platforms/kubernetes/#agent-resource-limits
  resources:
    requests:
      memory: 16Mi
      cpu: 1m
    limits:
      memory: 64Mi
      cpu: 100m
  
  securityContext:
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

  podMonitor:
    enabled: true
  
  customConfig:
    api:
      enabled: false
    sources:
      kubernetes_logs:
        type: kubernetes_logs
        auto_partial_merge: false
        extra_label_selector: vector.sources.kubernetes-logs/label=ingress-nginx
    transforms:
      stdout:
        type: filter
        inputs:
          - kubernetes_logs
        condition:
          type: vrl
          source: includes(["stdout"], .stream)
      parse_log_ingress_nginx:
        type: remap
        inputs:
          - stdout
        source: |
          structured =
            parse_regex!(.message, r'^(?P<nginx_remote_addr>\S+) - (?P<nginx_remote_user>\S+) \[(?P<nginx_time_local>[^\]]+)\] "(?P<nginx_request>[^"]+)" (?P<nginx_status>\d+) (?P<nginx_body_bytes_sent>\d+) "(?P<nginx_http_referer>[^"]+)" "(?P<nginx_http_user_agent>[^"]+)" (?P<nginx_request_length>\d+) (?P<nginx_request_time>\d+\.\d+) \[(?P<nginx_proxy_upstream_name>[^\]]*)\] \[(?P<nginx_proxy_alternative_upstream_name>[^\]]*)\] (?P<nginx_upstream_addr>[0-9\.a-z/]+:[0-9\.a-z/]+(?:, [0-9\.a-z/]+:[0-9\.a-z/]+)*) (?P<nginx_upstream_response_length>\d+(?:, \d+)*) (?P<nginx_upstream_response_time>\d+\.\d+(?:, \d+\.\d+)*) (?P<nginx_upstream_status>(?:\d+|-)(?:, (?:\d+|-))*) (?P<nginx_req_id>\S+)$')
          . = merge(., structured)
    # sinks:
    #   debug:
    #     type: console
    #     inputs:
    #       - parse_log_ingress_nginx
    #     target: stdout
    #     encoding:
    #       codec: json
