apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bucket-s3
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgAvxn4lLj68ye11qvoHBuH1hHcpF0KH6oB520oxNedptiGGpGhRQ+rbPu/+8oerzid+FmSVLLYWfrsna+wKOQo4F6mkskUdHNnTjij+3jeeW0bJ6lM2wlIqb+49EUuRI1u5NFYQaJL6AtnoZycIRsFlyxmBuQtxLWNf4sOA8KpcLlb2DUDBVj5moNnLAQ7sinEzF6yvLx9/fh7sPHN9fz+XvgjP4163fYIYksG6RmIqu24F7vFGh/jQpZh2+gvce+IXyyIIj4Qjm+C8UCvvN6YYoCS7CPLm7vlrIkGCRG0HsiA4MRyyHcs6jLt8rhCeDQVaDtQIwLsAXLDODKylkp0ilw7luLnoIsHAIaTAog5d1A3ovavmLZv02xu6iWbTTTQtOFtHdd2g8+4CJw+2BzdCNqqA7lyuC5TyEcEWaUiRHS/Uu5paBvbcW2RU6OBSviUUCEnBp5Awhv0xSx8l5cUEqY2Bz9DR+qj8vowgr1PwUQVAydcsfXu8iW4uCCLIRc7WGebBwfJtt7MMgbViTsMrw/G4HYGi0gZPsRHCgNFqVvceZmgPq4fBJXv6R4ZP161GQzYPmZA38MSPYwfsOfN6JCofmoJbvrYURr8EY6vDN7g+aislbvJhyWdEdGuh23jswHK59rePeWq0xZAD6kkMPgQxfij+sVqtOUU/j4zkvLe94S4+Qh9p+rQ1pjb+tTyOhs1PvmrAXA==
    rootUser: AgCQZ3gUWSVVaYY34BJaSVFL0uxNl5/fMpPmv1cRs8ccUviHgW80X3XON3OPnMQuYPcEOMw6OJnrPctKfL/+m0t8DPOOZLiiPkvXPDJtZ66koTSN7nv6MNWxFGLvEkmttVafkIJPyLqvk+k3G3kayCs80jUQpJbmFBvWiTX/4UPR+A/NLxR1pBa/OT0TE7xWwXs6YgvjTp+B1R84Zyvr5Zrd7F2TMJzHxp4gbtIqKJfx/CKNBjgXKEujjkI+RRBLZJ/erfIU9JfNLf4VBmekR8OMZrtTcuEHNyQj13TgJRgakP6hlFIXNphxj8oxt9bmYUTbKesWhu3lTbFiKrdNjk0kc2OA14wGz2MWM5s/eG8AAkXY9oEXxGrAeCvT0Qa+syiSU0KwFyOeFj0dSPiWX9z21MzEldVu8eh4j6z7eIjApL+mqIDabqyRSD5JoSxfxIxPYfkMMO53pu8aTrQF7bTXwA2eRQVEijG4IjWGIsWZTrwylSz1uTbVLS1cDM3ncFg4OISLhLqim6RRJVNk4XKsiFlfHY1NqcDf08xB85s4u6R8QaBV9djzgIOli0b8y9kzDYvII6yCh0kna9haCsxR/CDv0Z+lrU+9YNfILsTQ440S39abSQTXg6A5meRgtNeIOUhv9WgKYKwaJzZR5m5FhGnbbRnHpUQNKHaGfxZRunwHcTzT/hg7yogxvjSZViZixVpscw==
  template:
    metadata:
      creationTimestamp: null
      name: bucket-s3
      namespace: minio
    type: Opaque
