ingester:
  extraArgs:
  - -config.expand-env=true
  extraEnv:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: bucket-s3
        key: awsAcessKeyId
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: bucket-s3
        key: awsSecretAcessKey
querier:
  extraArgs:
  - -config.expand-env=true
  extraEnv:
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: bucket-s3
        key: awsAcessKeyId
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: bucket-s3
        key: awsSecretAcessKey