apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: helm-chart-ingress-nginx-public
name: ingress-nginx
version:  4.11.3
repo: https://kubernetes.github.io/ingress-nginx
releaseName: ingress-nginx-public
namespace: ingress-nginx
includeCRDs: false
valuesFile: values-ingress-nginx-public.yaml
valuesMerge: override                                                               # merge, override or replace
valuesInline:
  controller:
    labels:
      vector.sources.kubernetes-logs/label: ingress-nginx
    config:
      enable-brotli: "true"                                                         # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-brotli
    ingressClassResource:
      name: ingress-nginx-public
      controllerValue: k8s.io/ingress-nginx-public
    ingressClassByName: true
    ingressClass: ingress-nginx-public
    admissionWebhooks:
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    service:
      externalTrafficPolicy: Local
      annotations:
        # https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations
        service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Ingress=ingress-nginx-public