apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metallb
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - cluster: kind
          url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-metallb'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/kube-components-stack/kustomization.git
        targetRevision: HEAD
        path: 'examples/template-override/{{cluster}}-override'
      destination:
        server: '{{url}}'
        namespace: metallb
