# reddit:       https://www.reddit.com/r/selfhosted/comments/mrbntm/introducing_authentik_an_sso_provider_focused_on/
# artifacthub:  https://artifacthub.io/packages/helm/goauthentik/authentik
# GitHub:       https://github.com/goauthentik/authentik
# docs:         https://goauthentik.io/docs/
# https://goauthentik.io/docs/installation/configuration/
# helm chart:   https://github.com/goauthentik/helm/tree/main/charts/authentik
# values:       https://github.com/goauthentik/helm/blob/main/charts/authentik/values.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: authentik-helm-chart
name: &name authentik
version: 2022.6.3
repo: https://charts.goauthentik.io/
releaseName: *name
namespace: authentik
includeCRDs: false
valuesFile: values.yaml
valuesMerge: override                 # merge, override or replace
valuesInline: {}
