apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: helm-chart-external-dns
name: &name external-dns
version: 6.12.1
repo: https://charts.bitnami.com/bitnami
releaseName: *name
namespace: external-dns
includeCRDs: false
valuesFile: values-external-dns.yaml
valuesMerge: override                 # merge, override or replace
valuesInline: {}
