apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory # https://acme-staging-v02.api.letsencrypt.org/directory
    # # https://cert-manager.io/docs/configuration/acme/#use-an-alternative-certificate-chain
    preferredChain: ISRG Root X1 # DST Root CA X3
    # Email address used for ACME registration
    email: MalibuKoKo@users.noreply.github.com
    # Name of a secret used to store the ACME account private key from step 3
    privateKeySecretRef:
      name: letsencrypt-private-key
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: ingress-nginx-admin