apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
bases:
- ../../base
generators:
- ../../base/helm-chart-ingress-nginx-admin.yaml
- ../../base/helm-chart-ingress-nginx-private.yaml
- ../../base/helm-chart-ingress-nginx-public.yaml
