---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomization-secret-generator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kustomization.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  kustomization.yaml: |
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    namespace: argocd
    secretGenerator:
    - name: kind
      type: Opaque
      options:
        disableNameSuffixHash: true
        labels:
          argocd.argoproj.io/secret-type: cluster
      literals:
        - name={{.Values.env.fromValues.CLUSTER}}-{{.Values.env.fromValues.ENV}}
        - server=https://kubernetes.default.svc
        - config={"tlsClientConfig":{"insecure":false}}