---
apiVersion: batch/v1
kind: Job
metadata:
  name: install-argocd
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kustomization.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 0
  template:
    spec:
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      volumes:
        {{- with .Values.volumesAndMounts.volumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - 
        name: kubectl
        command:
        - /bin/sh
        - -c
        - |
          /bin/bash <<'EOF'
            trap "kubectl delete clusterroles.rbac.authorization.k8s.io system:{{ include "kustomization.fullname" . }}" EXIT

            cd /tmp && 
            OS=$(uname | tr '[:upper:]' '[:lower:]') &&
            ARCH=$(uname -m | sed 's/x86_64/amd64/; s/aarch64/arm64/') &&
            mkdir -p $KUSTOMIZE_PLUGIN_HOME/khelm.mgoltzsche.github.com/v2/chartrenderer &&
            wget -qO- https://github.com/mgoltzsche/khelm/releases/latest/download/khelm-${OS}-${ARCH} > $KUSTOMIZE_PLUGIN_HOME/khelm.mgoltzsche.github.com/v2/chartrenderer/ChartRenderer &&
            chmod +x $KUSTOMIZE_PLUGIN_HOME/khelm.mgoltzsche.github.com/v2/chartrenderer/ChartRenderer

            declare TMP=$(mktemp --directory /tmp/kubectl.XXXXXXXXXX)
            set -euo pipefail
            set -x
            git clone https://github.com/${OWNER}/${REPO}.git --depth=1 --branch ${REF} --single-branch $TMP/${REPO}

            folder=core/crds
            for crd in $(curl -s https://api.github.com/repos/${OWNER}/${REPO}/contents/${folder}\?ref\=${REF} | jq -r '.[].name'); do
              kustomize \
                --stack-trace \
                --enable-alpha-plugins \
                --enable-helm \
                --load-restrictor LoadRestrictionsNone build $TMP/${REPO}/${folder}/${crd}/overlays/${CLUSTER}-${ENV} \
                | kubectl apply --server-side=true --force-conflicts -f -
            done

            folder=addons/crds
            for crd in $(curl -s https://api.github.com/repos/${OWNER}/${REPO}/contents/${folder}\?ref\=${REF} | jq -r '.[].name'); do
              kustomize \
                --stack-trace \
                --enable-alpha-plugins \
                --enable-helm \
                --load-restrictor LoadRestrictionsNone build $TMP/${REPO}/${folder}/${crd}/overlays/${CLUSTER}-${ENV} \
                | kubectl apply --server-side=true --force-conflicts -f -
            done

            folder=core/apps
            app=kube-system
            kustomize \
              --stack-trace \
              --enable-alpha-plugins \
              --enable-helm \
              --load-restrictor LoadRestrictionsNone build $TMP/${REPO}/${folder}/${app}/overlays/${CLUSTER}-${ENV} \
            | kubectl apply -f -

            app=argocd
            kustomize \
              --stack-trace \
              --enable-alpha-plugins \
              --enable-helm \
              --load-restrictor LoadRestrictionsNone build $TMP/${REPO}/${folder}/${app}/overlays/${CLUSTER}-${ENV} \
            | kubectl apply -f -

            for k in deployment statefulset daemonset;
            do
              for o in $(kubectl -n argocd get $k -l app.kubernetes.io/part-of=argocd -o jsonpath='{.items[*].metadata.name}');
              do
                kubectl -n argocd rollout status $k/$o
              done
            done

            cd /tmp
            kustomize --load-restrictor LoadRestrictionsNone build | kubectl apply -f -

            kubectl apply -f https://raw.githubusercontent.com/kube-components-stack/kustomization/${REF}/core-crds.yaml
            kubectl apply -f https://raw.githubusercontent.com/kube-components-stack/kustomization/${REF}/core-apps.yaml
            kubectl apply -f https://raw.githubusercontent.com/kube-components-stack/kustomization/${REF}/addons-crds.yaml
            kubectl apply -f https://raw.githubusercontent.com/kube-components-stack/kustomization/${REF}/addons-apps.yaml
          EOF
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","$TMP-c","kubectl delete clusterroles.rbac.authorization.k8s.io system:{{ include "kustomization.fullname" . }} 1>> /proc/1/fd/1 2>> /proc/1/fd/2"]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          {{- range $key, $value := .Values.env.fromValues }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        # securityContext:
        #   runAsNonRoot: false #true
        #   readOnlyRootFilesystem: true
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     drop:
        #     - ALL
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
          {{- with .Values.volumesAndMounts.volumeMounts }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
      restartPolicy: Never
      serviceAccountName: {{ include "kustomization.serviceAccountName" . }}
