---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
# automountServiceAccountToken: ?
metadata:
  name: {{ include "kustomization.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kustomization.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
