apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
bases:
- ../../base
generators:
- ../../base/helm-generator.yaml
patchesStrategicMerge:
- ../../base/job-ingress-nginx-admission-create-patch.yaml