apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: kube-prometheus-stack-helm-chart
name: &name kube-prometheus-stack
version: ""
repo: ""
releaseName: *name
namespace: *name
includeCRDs: false
valuesFile: values.yaml
valuesMerge: override                 # merge, override or replace
valuesInline: {}
