# artifacthub                                       https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
# github                                            https://github.com/kubernetes/ingress-nginx
# values.yaml                                       https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: helm-chart-ingress-nginx-admin
name: ingress-nginx
version:  4.4.0
repo: https://kubernetes.github.io/ingress-nginx
releaseName: ingress-nginx-admin
namespace: ingress-nginx
includeCRDs: false
valuesFile: values-ingress-nginx-admin.yaml
valuesMerge: override                                                               # merge, override or replace
valuesInline:
  controller:
    config:
      enable-brotli: "true"                                                         # https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#enable-brotli
    ingressClassResource:
      name: ingress-nginx-admin
      controllerValue: k8s.io/ingress-nginx-admin
    ingressClassByName: true
    ingressClass: ingress-nginx-admin
    allowSnippetAnnotations: true
    admissionWebhooks:
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    service:
      externalTrafficPolicy: Local
      loadBalancerSourceRanges: 78.244.0.0/14,37.1.232.0/21,37.8.160.0/19,37.160.0.0/12,158.255.112.194/32,54.77.161.131/32,54.72.69.139/32,54.76.126.49/32,54.77.166.29/32,3.250.209.51/32,54.219.59.241/32
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
        # service.beta.kubernetes.io/load-balancer-source-ranges: 78.244.0.0/14,37.1.232.0/21,37.8.160.0/19,37.160.0.0/12,158.255.112.194/32,54.77.161.131/32,54.72.69.139/32,54.76.126.49/32,54.77.166.29/32,3.250.209.51/32,54.219.59.241/32
        # service.beta.kubernetes.io/aws-load-balancer-type: nlb
        # service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"                  # deprecated since v2.3.0 release in favor of the new aws-load-balancer-attributes annotation
        # service.beta.kubernetes.io/aws-load-balancer-internal: "false"                                          # deprecated since v2.2.0 release in favor of the new aws-load-balancer-scheme annotation
        # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'                                        # Set to '*' to enable proxy protocol v2, relative doc : https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt
        # https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations
        # service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true         # 01/12/2022: don't works !
        # service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Ingress=ingress-nginx-admin      # tags are added after ELB provisioning step
        # service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"                                  # internal (default) or internet-facing. Do not edit the annotations after creating your service. If you need to modify it, delete the service object and create it again with the desired value for this annotation.
        # service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: proxy_protocol_v2.enabled=true