apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: helm-chart-ingress-nginx-private
name: ingress-nginx
version:  4.2.5
repo: https://kubernetes.github.io/ingress-nginx
releaseName: ingress-nginx-private
namespace: ingress-nginx
includeCRDs: false
valuesFile: values-ingress-nginx-private.yaml
valuesMerge: override                                                               # merge, override or replace
valuesInline:
  controller:
    ingressClassResource:
      name: ingress-nginx-private
      controllerValue: k8s.io/ingress-nginx-private
    ingressClassByName: true
    ingressClass: ingress-nginx-private
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
    service:
      externalTrafficPolicy: Local
      annotations:
        # https://kubernetes-sigs.github.io/aws-load-balancer-controller/latest/guide/service/annotations
        service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
        service.beta.kubernetes.io/aws-load-balancer-type: nlb
        service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: Ingress=ingress-nginx-private