# artifacthub                                       https://artifacthub.io/packages/helm/grafana/loki-distributed
# values.yaml                                       https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/values.yaml
# storage_config                                    https://grafana.com/docs/loki/latest/configuration/#storage_config
apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: loki-distributed-helm-chart
name: &name loki-distributed
version: 0.66.0
repo: https://grafana.github.io/helm-charts
releaseName: *name
namespace: loki
includeCRDs: false
valuesFile: values.yaml
valuesMerge: override                 # merge, override or replace
valuesInline:
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
  loki:
    structuredConfig:
      ingester:
        # Disable chunk transfer which is not possible with statefulsets
        # and unnecessary for boltdb-shipper
        max_transfer_retries: 0
        chunk_idle_period: 1h
        chunk_target_size: 1536000
        max_chunk_age: 1h
      storage_config:
        aws:
          s3: http://minio.minio.svc.cluster.local:9000/loki
          s3forcepathstyle: true
        boltdb_shipper:
          active_index_directory: /var/loki/index
          shared_store: s3
          cache_location: /var/loki/cache
          resync_interval: 5s
      schema_config:
        configs:
          - from: "2020-09-07"
            store: boltdb-shipper
            object_store: aws
            schema: v11
            index:
              prefix: loki_index_
              period: 24h
  ingester:
    affinity: ~
  distributor:
    affinity: ~
    # https://github.com/grafana/helm-charts/issues/157#issuecomment-919369654
    replicas: 1
    extraEnv:
    - name: MY_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    extraArgs:
      - -memberlist.bind-addr=$(MY_POD_IP)
  querier:
    affinity: ~
  queryFrontend:
    affinity: ~
  tableManager:
    affinity: ~
  gateway:
    affinity: ~
    tolerations: []
  ruler:
    affinity: ~
  indexGateway:
    affinity: ~
  memcachedChunks:
    affinity: ~
  memcachedFrontend:
    affinity: ~
  memcachedIndexQueries:
    affinity: ~
  memcachedIndexWrites:
    affinity: ~
