apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    devops-slack: AgByp+Kv5bDxN9nvPsZWNpn+QXwUG7fjMF5Re/Omj5hJTRqo0XTsnUUWC7zcCgYbBssJiW5T1EWm1qXt2IIaoUW7AxMmzbsECg6yYWXgFp26obtyBpMjixBdc0mwskfmvI3ifiPeBzxGbxDE9xApmk4dXkI23ybbixvggrmyztfr+tdvPWVq+9clQ+UtI70Yinc9hFN0knaD8McBJstVEYAIuQZIxvdh8vQg+VuCa/Ar3oKF0GG/yZy8MLMw5zt+1GRTEgFrGd7bGwI/sMbS+Ng0hQ5rzBY2o3m7ZtBOlIrq1cOV0c2H0ZdqdxBg3hsYz5kHvIhOaFIQ3MmhlH4gPNx+h27Geo0M1dKfH8ijYL5ESufihyQvHsbt1JNrBzgTmO5Gvnhu6gTgyPxpPX8fi7Rv4QQCzYxUMnXTN2WgDjykWIIsWtjfNeqahR/TFvZ+4U/2Q9jd9TRQAns8l+URIs8TY8u7A5msxBW63aEkATyvED1Du44LeGj1AyYBdmtDUk6U3SueIo/9dlpT9WPH5aX1NxR8SkQDzsKcK0T6TkYHV0m46tr1xgnhF0MgI+MCm3Tw5dK0Kjz5f9exZG9HxmMHeXUuuzv2LbDqVAwTquF1VGDw2NjBU8U02SR7MT3Q34syB8XXGcRXG6sVC8vUpnzA2mqO5CkCgU+9E6ox9NtTyANmbP1HNDyLgIJ6aWp6yKEjkxsFN2RTKjZoJPvT20xZEnqkYolLpRJlxMRX7UnHfR6McUIj5xYw/j+tLGkqoYYdQ0Rv1w5eLxs=
    devops-teams: AgBYCrk3D/Rngpe5PPyEUkm8HGTIMrZrj0/91RpVwDWYFBvVXZ5A9v2ZWEAhOk+0w8az+RqRXoKb4OXlSh72F/9p6YYf446SIeV5zaOGRxNanDPI1ynAwfGfT0MauD39HehibVqHumvSGKymr8IfTTnWNTdePlqktMgYJoJJI/uzheIGSYec93YFan1hjardLykvdMX+F/9nneg/1JOdCz/5PlV8jkTSXQ7y4iJj4CJl69wVe7h6ycH0sIbqCSSURYPUOg5NFgs2gM6SCx9AKtCR/0q5gFIyfCRTf5JAHtGEB4CXzZTl0E39W6DUKam1xFNf/KRruPUyOk0h07fMFRvw+D8nzclN5Lv+LkkZGRmWFhVBd0MjQUp1gyfVjlwfWAH3pOpidHlDCfNYwZ8wayyKbtSeir8V5wN5g/tBVe756V/9uYK2kqol0LDKT/gYPbX381sautZ1PxgaCTzk2oIJHzlt0/ZMHQo7+/4CepYxPn0jk9UnM5Oqp4ofiffM28QdwMnbygMUG5HfiPnvTl7nwL7tzh6h0CS7rPcqX8Qjl6L3m6oZqNkKOriq3UL2EtJouripBnDrGbPXJl2vnq8Sgc4V2GGzVc6eqEMM0nQ6Ecd1Dr8/r4czq6xCviqHF/dBl89pp0qnBv9VeQUdhYUF66+7vy/Ev0pFpV3RU8AOFkIFx7KOx14HHT0+cU9bngfXn+Ptjh+V+ikSfkRTl2krVDOUCf1F/PXT01fuGTVIgrOCVnKqyme0hZVUvchqHyYgCi3s5JR9qHYpUUv8QnO+zr1/5CAee2cOd9Tb4C5e+WVbMvdUXh5IISIq83GGlSmHkpVZQIVFihmDTs89KKqdlZkAHQgf9fPGnKHnblLHavcLVB8ZJzyRZBA0yklnrNy6sVKX98D4awgoBUUOXPigQPK/d8RYRB3aYqDuI5yXJdT63xQA0+9n38jdLdZA67RUs+vhbLQz27v9vA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: argocd-notifications-secret
      namespace: argocd
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgCNA4O0l4kJMl2UM9CwZE36Mca0nSBunSI2h0H4A8v4QfHPoHh/plQimWg869YcWRkNaLwI2nzR3Emd1QocNqEXs9u90MFRA1HROJyIKrG4KXHMg5AfkgO87NOsY4r6S2TerArnL8UIzdnzp9ehogrbLhlBdtYu+FzKfLsg6TEnSx6MgNabi0eV0dUR/6A7Vrsbi5L8zGyRiDQzodAPSqF6z3Pl7wnG4DF8aDhcXZ2+naCWX4xiVAQ14klRydpox6hQtdqx2nsT575NMRqA5eySfiMCATNPAIxpkGU3+Ja+SeqA9cyOjmfl14wj7nP4Bv0S2HoeF+iPGpVv/HsE5c4OZaDKJ/pj1gGg1tlK5i2ioFvnT6fJb3HF4IsrIbD3HelNHT6hfame8OWYdggdIhtb2Fu3EWvRseV3AI1kuHHOkSrjldKdKZD9gSQbUmY1/I6hGAw+AscrnzagmUW1V3824vpFgdUu+xjr1J6N0StvXmtDTMmWOTTTJJt74NZEMj3rJW0IFdjeIlnGBlD2EAiyzOZst4+5A2tfmzsxGnenfgcwvJVvbrbUXGH5pVwBwZVY6yhD0t4E/b3mJ93ANXuJCLpzDqxZ+MMwgM77sWjRzc6/tua07hhmBC6rlPNOagGMb/naaPxMoPehM902Y9BaVbGm4SBxkvRef8s8u9PS7bbNxGPU4kw2+azPlfIFhHVcbnNVNbn7f3tRAErfeC6ljpWRcIFqCkjwucTP7iid6U9W7cQc7M4T46VL17bmANVuNndsLkR5/EobaaM=
    admin.passwordMtime: AgBMjbvSuihEP84DreihyKV8BqOs55V+nHSzyoCRDwxql+c5pS3LcKmD8yFacJ7uKUu3Dn+9P6YDi3qF0i5rUBVNqb7pFXQ2QtCL5ljpGvnPpZTU9NgRmRXLsZVnIrkGY608CGrvBHybWgea/NMh7gayHk0B4waggdzDOktzUTiqSaG2Jl5QMGFcR9XlAaZKyEh2yLArfPbob/VYNLMncx+j0rFPH44U1ExerE9NlmN7JhQdSEy3zggm9kiz1pOAci+5wUsSRgvc654YnYhg6/uD7x/SXs89lgPwZhbKc8viJyjkpuz7jeJKC/JyOcXb4I1o61QQL/bI46MKxmgPvaJmPuYzdMkZSWVm6wfxDSc8GIU406ds6aoX/cWVlmDOmIpyyZXnpGUQKJXypH5cBlMFIb7fwsF9OSL++4MvrK5c8dmW2tV1lQAG02kJ1MsLhhKd+wG5re6piC5fNnMtOWPY/Qs7BXWuGmOTyTh9uZGCe7S0z3mNUS4rK4CsLollR/U7rfoqdq3fG3H9pRrHfmoW2YNJNW6k/iKMEg5nCBjrT1eTk+bzk4fRCVtoPF/SKjXcIKP/ZckcuDwM7dJtDwZvEOpTXIjQ3HL4nTTDrzn2XRiuSkkWN21qRDvD4Tz6Xcq/kqQy827WgOPoFIuU1EUAJxzd/RIg5xqreMayITECldUhKl2+GlJ0h3kmKwWdPSJKbjdCqO40HlmGefm1qbkBPxtoaw==
    server.secretkey: AgCvutap0XZE5wwz5FUFxvJvR2nyYW4nbwIf/ztKApDEzuCHsLyvvpGXFOifJRniyudMEVEpz5DPunnChIJUbDBkDv3DXntIXeucX6YrBXT3UzSUZFKFGde03+arHAnO0jmYfKd1HJmS/iCV9hKx7ZXXvJQ/XjUobHwKqLDV7fWvgoEFmsLjO0fbPgb8/TaU8knxkkmfkeujm+dDUOpOewO6OGrrF5hfz33k4zjSed3dA3ZPE9h10GMJgYu+tPw6dhkuxJ+DGLxuIEvInSUyVyb3DET61UmC45qOzH5AB7f9mz88h/VLw4IPUvrIzNxqnksbMl8MxrHZ6v05nuILwXEsmLXvTfdoBtSqd6qZPLjt5fxwS2ex00DPsmyUaOirnyljdt+k+N3X3C0IVcLUwzf0WUsw3ApQFcSb/dtC57RFQA9QNe2tgQ1BiNVhms6YQU+lqctXru04RtOyzpexj+Mzb1O7K64MZO/e48AFk2PPOFC39Eyu66ZnIYPPpCAvJliKcRipwlgaVRO33MjxdFoFhVo16KJG0wR22eCCRjuM1VWVuu5kr+nvy3A0n28n88rTezwJFweiwF4mLLXPuIcSdIDL7Nxp2yMJtkh3CwQqcSo2LkxQXGSwTTOtyHtWoj2A3ARp/fOXUKWhhhtGKhGubMK1TzvsSoc5lPDBMQGoKndiOmt1Puv5HjlZ8A7yAQtCrV5ynJ1o3P3HHtW7J5FnAY9cVpNKLGV4vOpYCv+FHJ/WSAJM1tSE3Lbhkw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: argocd-secret
      namespace: argocd
    type: Opaque

---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: argocd
spec:
  encryptedData:
    admin-password: AgClvXCchJtEGXTgMp+33TZeD24TI7GAkweAYfZ+Ul21BDaDfOEP/eJGvfxlqYs0NGMJRXkYkX1N4UxPOgw7In128jxBTgJVEijj1RA5rTq8qv20jaJIoXwzkBOM7/dK2InTDc+esxbChyJpQivIUU+SacvvDw+xnM9I9/sq1DpS86XGKBURpk34PbP4hX6K9lwzs8Evo+pPaFgAszBCW0l80SeFbBJ0k6AMvfBdzjlfETkoI46YU5tffgDq7/WSPboHb+nL2bzNf9f1UqwxKPLQkjopJeRqNsQ1AMwdURy4AMfa/Nwr2Q1a3OE2jkeRBTJWLgbrsuHLK2XP794hcCkOr42zgc+TnojuHbjT/55hj2TObg0jBwWdlD6I8EkA3qpsEa3UgD/68OBUtA4hRgPpt4hWqFhFwTgO4XZ4YhBnXFUUXhr2E/6oVQUadL1p3mFqtdxU8MnVghL1d9TXOSvOaU6NqyAF9M6/gN96Jlmi/LjM8Z4i7++JC3Pi+OxY6a+kV1ceWbRm4VyL+fU06SP3K6MloPW89D6q+3tbz/L1wwTa/o5xIoICVTxv5/mzsh7vsXMADbFTABwi9l40R7T3btCtOJcjJdbF4RVBZoK02bxv65qNtx4GZRicOdrCOyDrObCbKdNf9EvyF1+tUIG/0adQFjJajzkW3dnRO/1EnfRKV/OiNN45ZMXB7aFw/qBFzwBMMg==
    admin-user: AgBhOH3a9RqIIMc57FGGCi0dwK9pWLT4LS1422ccCDkHc1o98KVcvybwdH+0YxWg+iSvMSdyO6P9gTm8LFUylfPjY936KNtPJS6+wbgCWmnjZnW1o0MauXLFaM2NhpSjuFhbMNV5LIEj6ywvKHUOe2zRwuEs+t6yKmTLTaJvQ6lWlF8Ak1hls0HVgT/no3H7ubdY5raFwyGQe7z/QC7bq3AEUOyJMY8ICAq/hXLtsyJlb7Rsru+UiuZHg9MpUTG4FQPk8ssYdCDKt7c+yh6yb4mynK7aW7cLsyvBPwc7GIifgs3EOgjjmDNykIN20ed7WCG2FPTDWFGm9c5qn/eMwlzkBiv8cMnWRf389/SwMrmE+Eadlg67rhhPaWPNKqap3kkLbsi2zxDX9OAyIaMs2ZVmKnc4cJ6Q5erZ4P+mYsfU4JGtnrKbyLQLd2ueaLoOPdDvG2GADaXCvu+iM8MwECHPw38/07s2BHU/pjWT76UBGZALlrwX9XSXPawI8Axp5CwBi22QzsxhoSFRwFNDkrcwC+zFurnKheNBcYnWtRPwAPi9EhRvNkW9cXw1jSQ4HYagbHV3V9M4YJSe/kdWTArrZ6hPmhV8ezmo/3hhdNgjLLy1Rs99or1Fs7CJgcFVqkyMn59iHcIoDuG33BcLZLSceSBDXeeG6JMe9dwpedPBu4KbD5E/mY8DVofRn7O7KBDrHHRqDA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: argocd
    type: Opaque

