notifications:
  argocdUrl: https://argocd.k8s.lan
  enabled: true
server:
  ingress:
    enabled: true
    ingressClassName: nginx-01
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
    - argocd.k8s.lan
    tls:
    - secretName: argocd-tls-certificate
      hosts:
      - argocd.k8s.lan
  config:
    url: https://argocd.k8s.lan
    application.instanceLabelKey: argocd.argoproj.io/instance
    oidc.config: |
      name: authentik
      issuer: http://authentik.k8s.lan/application/o/argocd/
      clientID: 8811b3aa63f19133ec84534482df81a5332dcfc1
      clientSecret: 8c5821c80264b81c483b932e2614fd848c3f2a7161470b1b74e3373c922dc35ab882581a5ed16fc159fc15fd6c93b8068e8e45c090cd5430167c7be2363920f3

      # Optional set of OIDC scopes to request. If omitted, defaults to: ["openid", "profile", "email", "groups"]
      requestedScopes: ["openid", "profile", "email", "groups"]

    #   # Optional set of OIDC claims to request on the ID token.
    #   requestedIDTokenClaims: {"groups": {"essential": true}}

    # dex.config: |
    #   logger:
    #     level: debug
    #     format: json
    #   connectors:
    #   - 
    #     type: oidc
    #     id: authentik
    #     name: authentik
    #     config:
    #       issuer: http://authentik.k8s.lan/application/o/argocd/
    #       clientID: 8811b3aa63f19133ec84534482df81a5332dcfc1
    #       clientSecret: 8c5821c80264b81c483b932e2614fd848c3f2a7161470b1b74e3373c922dc35ab882581a5ed16fc159fc15fd6c93b8068e8e45c090cd5430167c7be2363920f3
  rbacConfig:
    policy.default: role:readonly
## Argo Configs
configs:
  secret:
    # -- Create the argocd-secret
    createSecret: false