apiVersion: khelm.mgoltzsche.github.com/v2
kind: ChartRenderer
metadata:
  name: argo-cd
  namespace: argocd
repository: https://argoproj.github.io/argo-helm
chart: argo-cd
version: 7.6.12
include:
- apiVersion: apiextensions.k8s.io/v1
  kind: CustomResourceDefinition
kubeVersion: 1.22.0
values:
  ## Custom resource configuration
  crds:
    # -- Install and upgrade CRDs
    install: true
    # -- Keep CRDs on chart uninstall
    keep: false
    # -- Annotations to be added to all CRDs
    annotations: {}