apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
bases:
- ../../base
- ../../base/storage-classe-ebs.yaml
generators:
- ../../base/helm-generator.yaml
- ../../base/helm-generator-metrics-server.yaml
# - ../../base/helm-chart-aws-ebs-csi-driver.yaml
# - ../../base/helm-chart-aws-efs-csi-driver.yaml
